### ISSUE TITLE
[Request] 请问React Native接入，有Demo或者教程吗？

### ISSUE THREAD

**Issue by chj-damon** [bytedance/Bytedance-UnionAD#100]
## Is your feature request related to a problem? Please describe. | 提出这个建议是因为遇到了什么问题？
现在要在react-native开发的APP里面接入头条的广告，请问有相关的教程或者Demo吗？

## Describe the solution you'd like. | 描述你期望的解决方案。
A clear and concise description of what you want to happen. | 请简明清晰地描述你期望的解决方案。
期望有一个Demo可以参考，或者有一个插件可以直接在项目中使用

## Additional context | 额外信息
Add any other context or screenshots about the feature request here. | 如果有必要，请留下和建议有关的额外信息或截图。

**Comment by xzjxylophone** [comment]
不好意思，目前不支持RN Demo.
