### ISSUE TITLE
[BUG] 强制旋转屏幕至横屏后退出，点击广告进入网页时会是横屏

### ISSUE THREAD

**Issue by c344081** [bytedance/Bytedance-UnionAD#101]
## Describe the bug | 问题描述

强制旋转屏幕至横屏后退出为竖屏，此时点击广告进入网页会是横屏， 设备没有打开自动旋转

## Environmental information | 环境信息
 - SDK version: | SDK 版本： 3.1.0.9
 - Device model: | 设备型号： iPhone 6S
 - iOS version: | iOS 版本： 14.0

## To Reproduce | 如何复现
使用uidevice 进行强制旋转

**Comment by xzjxylophone** [comment]
能否把Demo中上传到你自己的 github 上了？
