### ISSUE TITLE
pod 能否实时同步官网？

### ISSUE THREAD

**Issue by chebanyun** [bytedance/Bytedance-UnionAD#103]

**Comment by chunxige** [comment]
8天前就提了这个issue，到现在还没同步，这么懒吗

**Comment by WillieWangWei** [comment]
请问“pod 能否实时同步官网”是指 pod 遇到了问题还是官网遇到了问题？是什么样的问题？

**Comment by cenaczx** [comment]
> 请问“pod 能否实时同步官网”是指 pod 遇到了问题还是官网遇到了问题？是什么样的问题？

官网已经更新到3.3.0.2版本 pod这边还是只有 3.2.6.2

**Comment by patgdut** [comment]
> 请问“pod 能否实时同步官网”是指 pod 遇到了问题还是官网遇到了问题？是什么样的问题？

不同步啊，希望这边的更新能及时一点。

**Comment by weigzhong** [comment]
pod已更新同步最新版本
