### ISSUE TITLE
[BUG] 视频类型的广告 视频播放时没有声音,广告点开后有声音

### ISSUE THREAD

**Issue by jeffasd** [bytedance/Bytedance-UnionAD#104]
## Describe the bug | 问题描述
A clear and concise description of what the bug is. | 请简明清晰地描述你遇到的问题。

## Environmental information | 环境信息
 - SDK version: | SDK 版本： [e.g. 3.3.0.0 | 比如：3.3.0.0]
 - Date and time: | 日期与时间： [e.g. 2020-01-01 21:00 | 比如 2020-01-01 21:00]
 - Device model: | 设备型号： [e.g. iPhone X | 比如：iPhone X]
 - iOS version: | iOS 版本： [e.g. 13.0 | 比如：13.0]

## To Reproduce | 如何复现
Steps to reproduce the behavior. | 如果可以的话，请描述如何复现这个问题。

## Screenshots | 截图
If applicable, add screenshots to help explain your problem. | 如果有必要，请在这里粘贴问题相关的截图。

## Backtrace | 相关堆栈
Please paste the backtrace related to the Bug. | 如果可以的话，请在这里粘贴问题相关的堆栈信息（已符号化、可读）。

## Additional context | 附言
Add any other context about the problem here. | 请留下你认为可以帮助解决这个问题的任何信息。

**Comment by WillieWangWei** [comment]
问题已解决：媒体方后端配置错误。
