### ISSUE TITLE
[BUG] 开屏广告和信息流广告会导致主线程阻塞

### ISSUE THREAD

**Issue by bianlius** [bytedance/Bytedance-UnionAD#106]
## Describe the bug | 问题描述
开屏广告和信息流广告会导致主线程阻塞

## Environmental information | 环境信息
 - SDK version: | SDK 版本： 3.3.0.4]
 - Device model: | 设备型号： iPhone X
 - iOS version: | iOS 版本： iPhone OS 13.3

## Backtrace | 相关堆栈

启屏：
Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, scene-update watchdog transgression: application<com.swx.weather.app>:360 exhausted real (wall clock) time allowance of 10.00 seconds | ProcessVisibility: Foreground | ProcessState: Running | WatchdogEvent: scene-update | WatchdogVisibility: Foreground | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 14.680 (user 14.680, system 0.000), 8% CPU", | "Elapsed application CPU time (seconds): 0.282, 0% CPU" | )
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x000000019a8aa8b8 __ulock_wait + 8
1   libdispatch.dylib             	0x000000019a7512a8 _dlock_wait + 52
2   libdispatch.dylib             	0x000000019a7511f0 _dispatch_once_wait$VARIANT$armv81 + 120
3   TQWeatherQA                   	0x00000001033222bc +[BUUSettingService service] + 56
4   TQWeatherQA                   	0x0000000103353db8 -[BUSplashAdView initWithSlotID:adloadSeq:primeRit:frame:] + 116
5   TQWeatherQA                   	0x0000000103236204 __57-[ATTTSplashAdapter loadADWithInfo:localInfo:completion:]_block_invoke + 5792260 (ATTTSplashAdapter.m:58)
6   libdispatch.dylib             	0x000000019a77e610 _dispatch_call_block_and_release + 24
7   libdispatch.dylib             	0x000000019a77f184 _dispatch_client_callout + 16
8   libdispatch.dylib             	0x000000019a76234c _dispatch_main_queue_callback_4CF$VARIANT$armv81 + 996
9   CoreFoundation                	0x000000019aa305e4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
10  CoreFoundation                	0x000000019aa2b5d8 __CFRunLoopRun + 2004
11  CoreFoundation                	0x000000019aa2aadc CFRunLoopRunSpecific + 464
12  GraphicsServices              	0x00000001a49b0328 GSEventRunModal + 104
13  UIKitCore                     	0x000000019eb25ae0 UIApplicationMain + 1936
14  TQWeatherQA                   	0x0000000102cbd348 main + 54088 (TQAppDelegate.swift:18)
15  libdyld.dylib                 	0x000000019a8b4360 start + 4

信息流：
Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, scene-update watchdog transgression: application<com.swx.weather.app>:3536 exhausted real (wall clock) time allowance of 10.00 seconds | ProcessVisibility: Foreground | ProcessState: Running | WatchdogEvent: scene-update | WatchdogVisibility: Background | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 139.020 (user 139.020, system 0.000), 7% CPU", | "Elapsed application CPU time (seconds): 0.941, 0% CPU" | )
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001ab8c68b8 __ulock_wait + 8
1   libdispatch.dylib             	0x00000001ab76d2a8 _dlock_wait + 52
2   libdispatch.dylib             	0x00000001ab76d1f0 _dispatch_once_wait$VARIANT$armv81 + 120
3   TQWeatherQA                   	0x0000000100e273c4 +[BUUSettingService service] + 56
4   TQWeatherQA                   	0x0000000100eabf68 -[BUNativeExpressAdManager initWithSlot:adSize:] + 72
5   TQWeatherQA                   	0x0000000100d3fb44 -[ATTTNativeAdapter loadADWithInfo:localInfo:completion:] + 5847876 (ATTTNativeAdapter.m:75)
6   TQWeatherQA                   	0x0000000100ce36a4 __123-[ATAdLoader loadOfferWithRequestID:placementModel:unitGroupModel:finalWaterfall:startDate:extra:delegate:success:failure:]_block_invoke.520 + 5469860 (ATAdLoader.m:765)
7   libdispatch.dylib             	0x00000001ab79a610 _dispatch_call_block_and_release + 24
8   libdispatch.dylib             	0x00000001ab79b184 _dispatch_client_callout + 16
9   libdispatch.dylib             	0x00000001ab77e34c _dispatch_main_queue_callback_4CF$VARIANT$armv81 + 996
10  CoreFoundation                	0x00000001aba4c5e4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
11  CoreFoundation                	0x00000001aba475d8 __CFRunLoopRun + 2004
12  CoreFoundation                	0x00000001aba46adc CFRunLoopRunSpecific + 464
13  GraphicsServices              	0x00000001b59cc328 GSEventRunModal + 104
14  UIKitCore                     	0x00000001afb41ae0 UIApplicationMain + 1936
15  TQWeatherQA                   	0x00000001007b9034 main + 53300 (TQAppDelegate.swift:18)
16  libdyld.dylib                 	0x00000001ab8d0360 start + 4

## Additional context | 附言
可能启屏广告和信息流请求同时请求导致

**Comment by HCongByte** [comment]
请问能提供一些具体的使用场景和流程吗
