### ISSUE TITLE
iPhone 12系列设备上 开屏广告，跳转按钮无法点击，被状态栏遮挡了

### ISSUE THREAD

**Issue by chunxige** [bytedance/Bytedance-UnionAD#107]
![Simulator Screen Shot - iPhone 12 - 2020-11-06 at 14 31 31](https://user-images.githubusercontent.com/8032681/98336855-a4381000-2042-11eb-917e-2305231bad7e.png)

**Comment by chunxige** [comment]
版本是：3.3.0.5

**Comment by weigzhong** [comment]
这个问题您更新到平台最新版本可以解决iphone 12设备上遮挡的问题
