### ISSUE TITLE
Readme 文件需要实时更新

### ISSUE THREAD

**Issue by chunxige** [bytedance/Bytedance-UnionAD#108]

**Comment by WillieWangWei** [comment]
请问 Readme 文件需要更新什么内容呢？

**Comment by chunxige** [comment]
更新和官网一样的版本描述信息，有时候很滞后，官网更新和github上的sdk保持同步更新

**Comment by WillieWangWei** [comment]
请以官方文档为准：

https://www.pangle.cn/help/doc/5fc4f25f7b550100157c01d0
