### ISSUE TITLE
git stage file报错

### ISSUE THREAD

**Issue by destinyxxl** [bytedance/Bytedance-UnionAD#11]
pathspec 'Pods/Bytedance-UnionAD/Bytedance-UnionAd/Frameworks/BUAdSDK.framework/Resources' did not match any files

**Comment by antjumper** [comment]
> pathspec 'Pods/Bytedance-UnionAD/Bytedance-UnionAd/Frameworks/BUAdSDK.framework/Resources' did not match any files



> pathspec 'Pods/Bytedance-UnionAD/Bytedance-UnionAd/Frameworks/BUAdSDK.framework/Resources' did not match any files

请问这个问题怎么解决的呀
