### ISSUE TITLE
[BUG] bugly检测到SDK有卡顿调用

### ISSUE THREAD

**Issue by aiquantong** [bytedance/Bytedance-UnionAD#114]
## 问题描述
 bugly检测到SDK有卡顿调用

## Environmental information | 环境信息
 - SDK version: | SDK 版本： 2.9.5.6
 - Date and time: | 日期与时间：2020-12-08 08:09:24
 - Device model: | 设备型号： iPhone Xr
 - iOS version: | iOS 版本： 14.0 (18A373)

## To Reproduce | 如何复现
 bugly检测

## Screenshots | 截图
无

## Backtrace | 相关堆栈

0 libsystem_kernel.dylib | __ulock_wait + 8
-- | --
1 libsystem_platform.dylib | __os_unfair_lock_lock_slow + 196
2 libobjc.A.dylib | _lookUpImpOrForward + 152
3 libobjc.A.dylib | __objc_msgSend_uncached + 68
4 TextInput | 0x00000001a23e0000 + 139848
5 TextInputUI | -[TUIKeyboardInputManagerMux setSystemInputManagerFromTextInputTraits:autofillMode:implProxy:] + 412
6 UIKitCore | -[UIKeyboardImpl setInputManagerFromCurrentInputMode] + 380
7 UIKitCore | -[UIKeyboardImpl setInputModeFromPreferences] + 396
8 UIKitCore | -[UIKeyboardImpl initWithFrame:forCustomInputView:] + 820
9 UIKitCore | +[UIKeyboardImpl sharedInstanceForCustomInputView:] + 140
10 WebKit | WebKit::TextChecker::isSmartInsertDeleteEnabled() + 32
11 WebKit | WebKit::WebProcessPool::createWebPage(WebKit::PageClient&, WTF::Ref<API::PageConfiguration, WTF::DumbPtrTraits<API::PageConfiguration> >&&) + 2276
12 WebKit | -[WKContentView _commonInitializationWithProcessPool:configuration:] + 72
13 WebKit | -[WKContentView initWithFrame:processPool:configuration:webView:] + 172
14 WebKit | -[WKWebView _initializeWithConfiguration:] + 1232
15 WebKit | -[WKWebView initWithFrame:configuration:] + 80
16 WebKit | -[WKWebView initWithFrame:] + 96
17 ShihuoIPhone | ___30-[BUUserAgentHelper userAgent]_block_invoke + 100
18 ShihuoIPhone | _bu_safe_dispatch_async_main_queue + 104
19 ShihuoIPhone | -[BUUserAgentHelper userAgent] + 76
20 ShihuoIPhone | +[BUNetInfoHelper userAgentString] + 56
21 ShihuoIPhone | -[BUBaseRequest requestHeaderFieldValueDictionary] + 60
22 ShihuoIPhone | -[BUNetworkAgent requestSerializerForRequest:] + 288
23 ShihuoIPhone | -[BUNetworkAgent sessionTaskForRequest:error:] + 172
24 ShihuoIPhone | -[BUNetworkAgent addRequest:] + 72
25 ShihuoIPhone | -[BUBaseRequest start] + 64
26 ShihuoIPhone | +[BUNetworkRequest requestWithURL:method:parameter:completionWithSuccess:failure:] + 192
27 ShihuoIPhone | -[BUUSettingService fetchSetting] + 2572
28 ShihuoIPhone | +[BUAdSDKManager setAppID:] + 316
29 ShihuoIPhone | +[SHBUADManager setupBUAdSDK] + 40
30 libdispatch.dylib | __dispatch_call_block_and_release + 32
31 libdispatch.dylib | __dispatch_client_callout + 20
32 libdispatch.dylib | _dispatch_main_queue_callback_4CF + 836
33 CoreFoundation | ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
34 CoreFoundation | ___CFRunLoopRun + 2508
35 CoreFoundation | CFRunLoopRunSpecific + 600
36 GraphicsServices | GSEventRunModal + 164
37 UIKitCore | -[UIApplication _run] + 1072
38 UIKitCore | UIApplicationMain + 168
39 ShihuoIPhone | _main + 136
40 libdyld.dylib | _start + 4

## Additional context | 附言
 bugly检测到SDK有卡顿调用

**Comment by WillieWangWei** [comment]
使用最新版 SDK 看下是否还存在这个问题？
