### ISSUE TITLE
[BUG] 3.4.0.0版本什么时候更新

### ISSUE THREAD

**Issue by www19949212008** [bytedance/Bytedance-UnionAD#116]

**Comment by weigzhong** [comment]
发版规则为：平台更新2～4周左右更新到pod上，请耐心等待

**Comment by Jdb156158** [comment]
看来3.4.1.0目前还是测试阶段，先不更新了，虽然后台上已经显示了3.4.1.0的下载版本。但是pod上还是老版本3.3.6.1版本，github上目前也是3.3.6.1版本。哈哈

**Comment by cenaczx** [comment]
Android 就能同步 为什么IOS会延迟这么久？

**Comment by nnianhou-** [comment]
希望能把最新版本同步更新到pod上。

**Comment by codeLifeDie** [comment]
官网都发消息要求更新 结果pod上新版本都还没搞好

**Comment by 740629515** [comment]
为啥pod上还是3.3.6.2版本啊..不是让20号之前更新3.4.2.3版本呢嘛..
