### ISSUE TITLE
iOS 13.0 crash：SKStoreProductViewController may not be subclassed

### ISSUE THREAD

**Issue by ArchLL** [bytedance/Bytedance-UnionAD#12]
```
*** Terminating app due to uncaught exception 'SKUnsupportedClassException', reason: 'SKStoreProductViewController may not be subclassed.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23b98a1c +[NSException raise:format:] + 188
	3   StoreKit                            0x00007fff2be99b53 +[SKStoreProductViewController allocWithZone:] + 274
	4   Hugo                                0x000000010661e930 -[BUAppStorePreloadItem initWithAppID:adID:logExtra:] + 249
	5   Hugo                                0x000000010661c371 -[BUAppStoreManager preloadAppStoreControllerWithAppID:adID:logExtra:isDuplicate:completion:] + 1022
	6   Hugo                                0x000000010661bdee -[BUAppStoreManager preloadAppStoreControllerWithAppID:adID:logExtra:completion:] + 136
	7   Hugo                                0x000000010661b296 +[BUAppStoreManager preloadAppStoreControllerWithAppID:adID:logExtra:completion:] + 138
	8   Hugo                                0x000000010665a792 __55-[BUNativeAd registerShowContainer:withClickableViews:]_block_invoke + 1743
	9   Hugo                                0x0000000106610a22 -[BUAdViewWitnessChecker checkoutViewTracker] + 811
	10  Hugo                                0x00000001066106c8 __49-[BUAdViewWitnessChecker checkAdViewsIfWitnessed]_block_invoke + 34
	11  libdispatch.dylib                   0x0000000109e92df0 _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x0000000109e93d64 _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x0000000109ea1e1c _dispatch_main_queue_callback_4CF + 1500
	14  CoreFoundation                      0x00007fff23afb699 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	15  CoreFoundation                      0x00007fff23af62f9 __CFRunLoopRun + 2329
	16  CoreFoundation                      0x00007fff23af56b6 CFRunLoopRunSpecific + 438
	17  GraphicsServices                    0x00007fff3815cbb0 GSEventRunModal + 65
	18  UIKitCore                           0x00007fff47162a67 UIApplicationMain + 1621
	19  Hugo                                0x0000000105573e60 main + 112
	20  libdyld.dylib                       0x00007fff5123bcf5 start + 1
	21  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by yuanzhiying** [comment]
也遇到了。
Trapped uncaught exception 'SKUnsupportedClassException', reason: 'SKStoreProductViewController may not be subclassed.' 
(
	0   CoreFoundation                      0x000000019c14b28c 6E8ED431-E507-3897-BF3A-AFD3D4C2C49F + 1225356
	1   libobjc.A.dylib                     0x000000019be740a4 objc_exception_throw + 56
	2   CoreFoundation                      0x000000019c040ac8 6E8ED431-E507-3897-BF3A-AFD3D4C2C49F + 133832
	3   StoreKit                            0x00000001aa9aaa48 43F8023B-D344-3404-928B-618FEC4D7F4A + 129608
	4   App-mobile                          0x0000000102937eb0 -[BUAppStorePreloadItem initWithAppID:adID:logExtra:] + 276
	5   App-mobile                          0x0000000102935a30 -[BUAppStoreManager preloadAppStoreControllerWithAppID:adID:logExtra:isDuplicate:completion:] + 1140
	6   App-mobile                          0x0000000102935444 -[BUAppStoreManager preloadAppStoreControllerWithAppID:adID:logExtra:completion:] + 148
	7   App-mobile                          0x00000001029348ac +[BUAppStoreManager preloadAppStoreControllerWithAppID:adID:logExtra:completion:] + 144
	8   App-mobile                          0x00000001029b2598 __41-[BUSplashAdView startTrackView:isCache:]_block_invoke + 1480
	9   App-mobile                          0x000000010292a130 -[BUAdViewWitnessChecker checkoutViewTracker] + 716
	10  App-mobile                          0x0000000102929e40 __49-[BUAdViewWitnessChecker checkAdViewsIfWitnessed]_block_invoke + 36
	11  libdispatch.dylib                   0x000000010abbd8ac _dispatch_call_block_and_release + 24
	12  libdispatch.dylib                   0x000000010abbec88 _dispatch_client_callout + 16
	13  libdispatch.dylib                   0x000000010abccce8 _dispatch_main_queue_callback_4CF + 1316
	14  CoreFoundation                      0x000000019c0c8c74 6E8ED431-E507-3897-BF3A-AFD3D4C2C49F + 691316
	15  CoreFoundation                      0x000000019c0c3c68 6E8ED431-E507-3897-BF3A-AFD3D4C2C49F + 670824
	16  CoreFoundation                      0x000000019c0c316c CFRunLoopRunSpecific + 464
	17  GraphicsServices                    0x00000001a5efb328 GSEventRunModal + 104
	18  UIKitCore                           0x00000001a012dd0c UIApplicationMain + 1936
	19  App-mobile                          0x00000001027d66dc main + 152
	20  libdyld.dylib                       0x000000019bf4e424 8F3A474D-45CC-3991-829F-77B3B151BA86 + 5156
)

**Comment by yh980237697** [comment]
请升级最新版本SDK解决
