### ISSUE TITLE
[BUG] cpu占用过高，被系统强杀

### ISSUE THREAD

**Issue by KorolZhu** [bytedance/Bytedance-UnionAD#124]
## Describe the bug | 问题描述
Action taken:     Process killed
CPU:  9 seconds cpu time over 13 seconds (71% cpu average), exceeding limit of 60% cpu over 15 seconds

## Environmental information | 环境信息
 - SDK version: | SDK 版本： 3.2.6.2
 - Date and time: | 日期与时间：2021-01-16 16:35:02
 - Device model: | 设备型号：iPhone 12 Pro
 - iOS version: | iOS 版本： 14.2

## To Reproduce | 如何复现
无法复现

## Screenshots | 截图
使用过程中闪退，没有截图

## Backtrace | 相关堆栈
[HelloTalk_Binary 2021-1-16, 4-35 PM.txt](https://github.com/bytedance/Bytedance-UnionAD/files/5833304/HelloTalk_Binary.2021-1-16.4-35.PM.txt)

## Additional context | 附言
崩溃之前有展示广告， Heaviest stack  显示的都是这个类的调用 HMDBUToBCrashTracker

**Comment by WillieWangWei** [comment]
HMDBUToBCrashTracker 是协助分析崩溃问题的类，并不是造成崩溃的原因
