### ISSUE TITLE
[BUG] Ads-CN 和 Ads-Global 没法同时使用

### ISSUE THREAD

**Issue by eroscai** [bytedance/Bytedance-UnionAD#126]
## 国内和国外都要使用时如何引入SDK？
文档里面貌似写着国内和国外都要使用时需要把 `Ads-CN` 和 `Ads-Global` 都接进来，但是实际使用pods方式引入的时候会报冲突，错误如下：

```
[!] The 'Pods-XXX_Example' target has frameworks with conflicting names: buadsdk.framework and bufoundation.framework.
```

请问如何引入才是正确的？你们的SDK是否支持同时引入？还是目前只能使用其中之一？

## Environmental information | 环境信息
 - SDK version: | SDK 版本： [3.4.2.3]

**Comment by Eason-yangyang** [comment]
PangleSDK支持国内外同时集成，但并非是Ads-CN与Ads-Global同时使用。详情请联系相关技术支持同学。

**Comment by yangsheng** [comment]
能不能在这个上面详细解答一下这个问题。因为app在国内和国外都有用户的情况下，怎么接入？谢谢

**Comment by Eason-yangyang** [comment]
> 能不能在这个上面详细解答一下这个问题。因为app在国内和国外都有用户的情况下，怎么接入？谢谢

https://www.pangleglobal.com/help/doc/6034adaebc3f04003eef5011?query=6034adaebc3f04003eef5011

**Comment by useobjc** [comment]
> > 能不能在这个上面详细解答一下这个问题。因为app在国内和国外都有用户的情况下，怎么接入？谢谢
> 
> https://www.pangleglobal.com/help/doc/6034adaebc3f04003eef5011?query=6034adaebc3f04003eef5011

同问这个问题。 @Eason-yangyang
链接坏了，直接跳转到 https://www.pangleglobal.com/support/doc/what-is-pangle
