### ISSUE TITLE
[BUG] 3.3.6.2 开屏广告点击卡死

### ISSUE THREAD

**Issue by ZexiFangkong** [bytedance/Bytedance-UnionAD#127]
## Describe the bug | 问题描述
     3.3.6.0 - 3.3.6.2 都出现了点击开屏广告卡死的问题
     CPU 爆满, 看堆栈应该是个死循环

## Environmental information | 环境信息
 - SDK version: | SDK 版本： 3.3.6.0 - 3.3.6.2 
 - Date and time: | 日期与时间： 2021.1.21
 - Device model: | 设备型号： iPhone8
 - iOS version: | iOS 版本：14.2

## To Reproduce | 如何复现
Steps to reproduce the behavior. | 如果可以的话，请描述如何复现这个问题。
启动 App 加载开屏广告, 加载成功后点击广告, 在这台手机是必现的, 其他手机暂时未发现相关问题

## Screenshots | 截图
If applicable, add screenshots to help explain your problem. | 如果有必要，请在这里粘贴问题相关的截图。

## Backtrace | 相关堆栈
Please paste the backtrace related to the Bug. | 如果可以的话，请在这里粘贴问题相关的堆栈信息（已符号化、可读）。
![image](https://user-images.githubusercontent.com/23274725/105353909-ce08d800-5c2a-11eb-89e2-d9ccad01665b.png)
![image](https://user-images.githubusercontent.com/23274725/105353915-d19c5f00-5c2a-11eb-8a39-c7bfd3f6bfa0.png)
![image](https://user-images.githubusercontent.com/23274725/105353921-d3feb900-5c2a-11eb-9927-efa5f387d1a0.png)

## Additional context | 附言
Add any other context about the problem here. | 请留下你认为可以帮助解决这个问题的任何信息。

**Comment by Bisond** [comment]
我这也是直接卡死了，还以为我集成的有问题。。。

**Comment by KorolZhu** [comment]
把sdk改为Ads-CN ，升级到3.4.2.8后，我也一样，点击开屏广告直接卡死

**Comment by KorolZhu** [comment]
卡死的问题找到了，是因为没有设置 BUSplashAdView的rootViewController
