### ISSUE TITLE
[BUG] 此服务器的证书无效。您可能正在连接到一个伪装成“210.22.123.80”的服务器，这会威胁到您的机密信息的安全。

### ISSUE THREAD

**Issue by zys-mining** [bytedance/Bytedance-UnionAD#130]
## Describe the bug | 问题描述
此服务器的证书无效。您可能正在连接到一个伪装成“210.22.123.80”的服务器，这会威胁到您的机密信息的安全。

## Environmental information | 环境信息
 - SDK version: | SDK 版本： 3.4.2.3
 - Date and time: | 日期与时间： 2021-02-20
 - Device model: | 设备型号： iPhone 7 Plus
 - iOS version: | iOS 版本： 14.3

## To Reproduce | 如何复现
加载完成BUNativeExpressAdView信息流广告之后会在控制台出现

## Screenshots | 截图
没有截图

## Backtrace | 相关堆栈
没有堆栈

## Additional context | 附言
Task <F7A84E9E-5DC2-4230-B10E-18E4C7F3485E>.<32> finished with error [-1202] Error Domain=NSURLErrorDomain Code=-1202 "此服务器的证书无效。您可能正在连接到一个伪装成“210.22.123.80”的服务器，这会威胁到您的机密信息的安全。" UserInfo={NSLocalizedRecoverySuggestion=您仍要连接此服务器吗？, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(0x10332a600) s: *.wostore.cn i: Secure Site CA>",
    "<cert(0x10333c600) s: Secure Site CA i: DigiCert Global Root CA>"
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://210.22.123.80/info-flow/card/report?channel=douyin_2&aid=1691936670354436&cid=1691936680403048&did=unkown&idfa=00000000-0000-0000-0000-000000000000&imei=&ip=111.201.226.64&callback=CISY4KHr2YADEOjAxabr2YADGIfH0euhjPAFIIfH0euhjPAFKI6Q0_PHr4ADMAw4uKqAwwNCKUI2NjlERkQyLUQ3QkItNDk4Mi1COUE5LTE1RTc4MTY4Rjg4RHUxNDE2SIDSk60DUAA&type=11, NSErrorFailingURLStringKey=https://210.22.123.80/info-flow/card/report?channel=douyin_2&aid=1691936670354436&cid=1691936680403048&did=unkown&idfa=00000000-0000-0000-0000-000000000000&imei=&ip=111.201.226.64&callback=CISY4KHr2YADEOjAxabr2YADGIfH0euhjPAFIIfH0euhjPAFKI6Q0_PHr4ADMAw4uKqAwwNCKUI2NjlERkQyLUQ3QkItNDk4Mi1COUE5LTE1RTc4MTY4Rjg4RHUxNDE2SIDSk60DUAA&type=11, NSUnderlyingError=0x2810381b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x282cf59e0>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9843, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9843, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x10332a600) s: *.wostore.cn i: Secure Site CA>",
    "<cert(0x10333c600) s: Secure Site CA i: DigiCert Global Root CA>"
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <F7A84E9E-5DC2-4230-B10E-18E4C7F3485E>.<32>"
), _kCFStreamErrorCodeKey=-9843, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <F7A84E9E-5DC2-4230-B10E-18E4C7F3485E>.<32>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x282cf59e0>, NSLocalizedDescription=此服务器的证书无效。您可能正在连接到一个伪装成“210.22.123.80”的服务器，这会威胁到您的机密信息的安全。}

**Comment by WillieWangWei** [comment]
是不是连代理了？

**Comment by zhoujiangod** [comment]
> 是不是连代理了？

没有哦。我是在真机上跑的
