### ISSUE TITLE
[BUG] 换了Ads-CN以后，开屏广告会启动跳我的APP主页以后再跳广告

### ISSUE THREAD

**Issue by kingstarwmx** [bytedance/Bytedance-UnionAD#131]
换了Ads-CN以后，开屏广告会启动跳我的主页以后(不到1s)再跳广告，以前是启动首先跳广告再跳app主页的

**Comment by KorolZhu** [comment]
@kingstarwmx 我换了Ads-CN（3.4.2.8）以后，点击开屏广告直接卡死，你会有这个问题吗

**Comment by WillieWangWei** [comment]
请问你用的 SDK 版本号是什么？

**Comment by Laixg** [comment]
之前我也有这个问题，只是我自己暂时处理了一下。就是把BUSplashAdView的背景颜色修改为不透明，但是这样也会有短暂的黑屏或者白屏，也可以在BUSplashAdView上自己加一个view，这个view的布局和启动页一样，这样应该就不会有问题了。这样只能做短暂的处理，等官方修复再升级版本即可

**Comment by hai3343** [comment]
> 之前我也有这个问题，只是我自己暂时处理了一下。就是把BUSplashAdView的背景颜色修改为不透明，但是这样也会有短暂的黑屏或者白屏，也可以在BUSplashAdView上自己加一个view，这个view的布局和启动页一样，这样应该就不会有问题了。这样只能做短暂的处理，等官方修复再升级版本即可

这样广告就没了啊

**Comment by wyt809225290** [comment]
> 换了Ads-CN以后，开屏广告会启动跳我的主页以后(不到1s)再跳广告，以前是启动首先跳广告再跳app主页的

请问这个问题解决了吗，我也遇到了一样的情况。

**Comment by Gluckyiyi** [comment]
我也有这个问题，并且在刘海屏上，广告是变形的
