### ISSUE TITLE
[BUG]内存过渡释放导致crash的问题

### ISSUE THREAD

**Issue by zhulintao** [bytedance/Bytedance-UnionAD#132]
## Describe the bug | 问题描述
接入穿山甲SDK后，开始收集到这个问题，在更新穿山甲版本到3.4.2.3之后，这个问题上报频率剧增

## Environmental information | 环境信息
 - SDK version: | SDK 版本： [3.4.2.3]
 - Date and time: | 日期与时间： [2020-03-22 21:00]
 - Device model: | 设备型号： [iPhone X]
 - iOS version: | iOS 版本： [13.0及以上]

## Screenshots | 截图
<img width="753" alt="截屏2021-03-23 下午3 55 41" src="https://user-images.githubusercontent.com/20701000/112112237-3acf2d00-8bf0-11eb-9493-aa5fb1b69ed8.png">

## Backtrace | 相关堆栈

#18 Thread
SIGSEGV
SEGV_ACCERR
0 libobjc.A.dylib | objc_release + 16
-- | --
1 CoreFoundation | ___RELEASE_OBJECTS_IN_THE_ARRAY__ + 112
2 CoreFoundation | -[__NSArrayM dealloc] + 272
3 libobjc.A.dylib | AutoreleasePoolPage::releaseUntil(objc_object**) + 180
4 libobjc.A.dylib | objc_autoreleasePoolPop + 224
5 Foundation | -[NSOperation start] + 1156
6 Foundation | ___NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
7 Foundation | ___NSOQSchedule_f + 180
8 libdispatch.dylib | __dispatch_block_async_invoke2 + 104
9 libdispatch.dylib | __dispatch_client_callout + 16
10 libdispatch.dylib | __dispatch_continuation_pop$VARIANT$armv81 + 404
11 libdispatch.dylib | __dispatch_async_redirect_invoke + 584
12 libdispatch.dylib | __dispatch_root_queue_drain + 344
13 libdispatch.dylib | __dispatch_worker_thread2 + 112
14 libsystem_pthread.dylib | _pthread_wqthread + 212

## Additional context | 附言
根据我们的日志跟踪发现，这个问题主要发生在开屏广告结束后，我们的开屏广告都是穿山甲广告

**Comment by leiwenya** [comment]
We have fixed this problem, please upgrade to the latest version.
