### ISSUE TITLE
[BUG] 编译ld找不到符号BUCNAuxiliary

### ISSUE THREAD

**Issue by skytoup** [bytedance/Bytedance-UnionAD#134]
## Describe the bug | 问题描述

编译ld找不到符号

    Undefined symbols for architecture arm64:
      "___cxa_current_primary_exception", referenced from:
          _hmdbu_current_cpp_exception in BUCNAuxiliary(hmdbu_cpp_exception.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Environmental information | 环境信息
 - SDK version: | SDK 版本： 3.5.1.0

**Comment by skytoup** [comment]
![image](https://user-images.githubusercontent.com/11342389/113814201-dc837c00-97a3-11eb-9157-4a808cc86500.png)

@Eason-yangyang @bytedance-tech

**Comment by MorningStarJ** [comment]
同问

**Comment by MrDomin** [comment]
Ads-CN.podspec
