### ISSUE TITLE
[BUG] 3.4.2.3 版本，iOS10闪退

### ISSUE THREAD

**Issue by onceMu** [bytedance/Bytedance-UnionAD#135]
## Environmental information | 环境信息
 - SDK version: | SDK 版本：3.4.2.3
 - iOS version: | iOS 版本： iOS10.0-iOS10.3.4

## Screenshots | 截图
<img width="1071" alt="截屏2021-04-08 下午3 36 48" src="https://user-images.githubusercontent.com/3349775/113986918-5d17aa80-9880-11eb-8b99-fe13ab0b3a45.png">

## Additional context | 附言
Add any other context about the problem here. | 请留下你认为可以帮助解决这个问题的任何信息。

**Comment by leiwenya** [comment]
We have fixed this problem, please upgrade to the latest version.
