### ISSUE TITLE
3.5.1.0 iOS刚cocoapods下来一编译就报错

### ISSUE THREAD

**Issue by vitasapple** [bytedance/Bytedance-UnionAD#136]
全新项目，刚用cocoapods下载下来，编译一下就报错了，连真机都还没跑起来，link binary with libraries都还没添加那些动态库，我看了下SDK版本是2天前的3.5.1.0
错误如下：
Undefined symbols for architecture arm64:
  "___cxa_current_primary_exception", referenced from:
      _hmdbu_current_cpp_exception in BUCNAuxiliary(hmdbu_cpp_exception.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by WillieWangWei** [comment]
跟此问题一致 https://github.com/bytedance/Bytedance-UnionAD/issues/134#issuecomment-814666223
