### ISSUE TITLE
[BUG] xcode集成报错

### ISSUE THREAD

**Issue by kingstarwmx** [bytedance/Bytedance-UnionAD#137]
xcode 12.4集成Ads-CN 3.5.1.0，直接编译失败，错误信息如下
Undefined symbols for architecture arm64:
  "___cxa_current_primary_exception", referenced from:
      _hmdbu_current_cpp_exception in BUCNAuxiliary(hmdbu_cpp_exception.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by 986138497** [comment]
是的,一样,更新后也报这个错, 你解决了吗

**Comment by kingstarwmx** [comment]
> 是的,一样,更新后也报这个错, 你解决了吗

好像M1芯片报这个错，我换英特尔电脑就不报错了

**Comment by 986138497** [comment]
不是,我是就是英特尔的,退个版本就行了

**Comment by WillieWangWei** [comment]
参考这问题 https://github.com/bytedance/Bytedance-UnionAD/issues/134#issuecomment-814666223
