### ISSUE TITLE
3510打包出错，低版本没有问题，还有个就是版本号能否跟官网介绍的版本号一一对应上

### ISSUE THREAD

**Issue by lkios** [bytedance/Bytedance-UnionAD#139]
Undefined symbols for architecture armv7:
  "___cxa_current_primary_exception", referenced from:
      _hmdbu_current_cpp_exception in BUCNAuxiliary(hmdbu_cpp_exception.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by WillieWangWei** [comment]
参考这问题 https://github.com/bytedance/Bytedance-UnionAD/issues/134#issuecomment-814666223
