### ISSUE TITLE
pod很慢很慢，大概等待了一上午成功了

### ISSUE THREAD

**Issue by xurigan** [bytedance/Bytedance-UnionAD#15]
pod不支持depend

**Comment by mcheng315** [comment]
遇到同样的问题

**Comment by xurigan** [comment]
显示没有某个方法都是他的库因为没有真正引用到项目中，你是怎么使用的？

**Comment by ChristingLi** [comment]
你需要给git配置代理。因为你访问git很慢，所以下载的慢。

**Comment by Li-Yudong** [comment]
pod 一直失败

**Comment by ChristingLi** [comment]
> pod 一直失败

给git配置上代理就行

**Comment by yh980237697** [comment]
有同学解决了，请参考下https://www.cnblogs.com/zjfjava/p/10392150.html
