### ISSUE TITLE
[BUG] iOS Ads-CN 4.3.0.5 新出现的崩溃问题, 启动app初始化广告平台就崩溃

### ISSUE THREAD

**Issue by TheRockLee** [bytedance/Bytedance-UnionAD#151]
## Describe the bug | 问题描述
A clear and concise description of what the bug is. | 
一直在使用穿山甲SDK, 作为AdMob的中介组引入, 之前很稳定, iOS Ads-CN更新到4.3.0.5之后, 线上出现新的崩溃, 量不大但是在持续上升中

## Environmental information | 环境信息
 - SDK version: | SDK 版本： iOS Ads-CN 4.3.0.5
 - Date and time: | 日期与时间： 2022-04-22
 - Device model: | 设备型号：线上上报各种机型都有
 - iOS version: | iOS 版本： 主要集中在iOS 15, iOS 14, iPadOS 15

## To Reproduce | 如何复现
Steps to reproduce the behavior. | 
自测没有复现

## Screenshots | 截图
If applicable, add screenshots to help explain your problem. | 
截图如下, 来自Firebase Crashlytics上报
<img width="646" alt="image" src="https://user-images.githubusercontent.com/15214531/164581099-fd7def41-e07e-4f6a-92c4-954d4762ec3b.png">

## Backtrace | 相关堆栈
Please paste the backtrace related to the Bug. | 
请看截图

**Comment by chenzhuozy** [comment]
We have fixed this problem, please upgrade to the latest version.
