### ISSUE TITLE
[BUG] BUPlistStorage setObject 崩溃

### ISSUE THREAD

**Issue by ruixingchen** [bytedance/Bytedance-UnionAD#153]
## Describe the bug | 问题描述
线上收集到很多该类型的崩溃，主要集中在iOS15.4， iOS15.5

## Environmental information | 环境信息
 - SDK version: | SDK 版本： 4.4.07
 - Date and time: | 日期与时间：
 - Device model: | 设备型号：各型号均有
 - iOS version: | iOS 版本：15.4 15.5

## To Reproduce | 如何复现
自测无法复线

## Backtrace | 相关堆栈
出错堆栈

0	libobjc.A.dylib
_objc_release + 16
1	CoreFoundation
_cow_cleanup + 172
2	CoreFoundation
-[__NSFrozenDictionaryM dealloc] + 124
3
___35-[BUPlistStorage setObject:forKey:]_block_invoke + 52
4	libdispatch.dylib
__dispatch_call_block_and_release + 32
5	libdispatch.dylib
__dispatch_client_callout + 20
6	libdispatch.dylib
__dispatch_lane_concurrent_drain + 992
7	libdispatch.dylib
__dispatch_lane_invoke + 504
8	libdispatch.dylib
__dispatch_queue_override_invoke + 496
9	libdispatch.dylib
__dispatch_root_queue_drain + 396
10	libdispatch.dylib
__dispatch_worker_thread2 + 164
11	libsystem_pthread.dylib
__pthread_wqthread + 228

## Additional context | 附言
同时线上还收集到相当多的启动SDK闪退
0	libobjc.A.dylib
_objc_release + 16
1
+[BU_IESGurdKit setupWithAppId:appVersion:cacheRootDirectory:] + 308
2
+[BUGeckoPreloadManager setupSDKWithTerritory:IESGeckoKitAppId:IESGeckoKit_CACHE_DIRECTORY:IESGeckoKitAccessKey:IESGeckoKit_Domains:ZipBlock:] + 292
3
___49+[BUAdSDKManager startWithSyncCompletionHandler:]_block_invoke_2 + 220
4	libdispatch.dylib
__dispatch_call_block_and_release + 32
5	libdispatch.dylib
__dispatch_client_callout + 20
6	libdispatch.dylib
__dispatch_queue_override_invoke + 784
7	libdispatch.dylib
__dispatch_root_queue_drain + 396
8	libdispatch.dylib
__dispatch_worker_thread2 + 164
9	libsystem_pthread.dylib
__pthread_wqthread + 228

**Comment by leiwenya** [comment]
We have fixed this problem, please upgrade to the latest version.
