### ISSUE TITLE
[BUG] Demo没有适配 4700 版本

### ISSUE THREAD

**Issue by iOSleep** [bytedance/Bytedance-UnionAD#158]
## Describe the bug | 问题描述
最新 demo 运行失败

## Environmental information | 环境信息
 - SDK version: | SDK 版本：4.7.0.8
 - Date and time: | 日期与时间： 2022-08-27 16:36
 - Device model: | 设备型号： iPhone 8plus
 - iOS version: | iOS 版本： 15.4

## To Reproduce | 如何复现
pod update 后运行项目

## Screenshots | 截图
If applicable, add screenshots to help explain your problem. | 如果有必要，请在这里粘贴问题相关的截图。
![QQ20220827-164131](https://user-images.githubusercontent.com/26478957/187022657-34a40f0c-480b-47b1-acfd-f830498a1a20.png)

**Comment by zhangjinlin** [comment]
改成什么样了，最垃圾的sdk，最垃圾的文档

**Comment by HCongByte** [comment]
给您带来的不便深表歉意，Demo目前已更新。
