### ISSUE TITLE
SDK2.4.6.3版本iOS13-Xcode11-BUNativeExpress广告无法显示

### ISSUE THREAD

**Issue by Ranger2627** [bytedance/Bytedance-UnionAD#16]
SDK版本：2.4.6.3
Xcode11.0——iOS13.0
BUNativeExpressBannerView，BUNativeExpressInterstitialAd均能够在各自的delegate中进行success回调。但是无法加载广告
其中BUNativeExpressInterstitialAd类的isAdValid属性在success回调后仍然是NO
希望能够尽快处理

**Comment by jinjinanan** [comment]
你好 你的解决了吗

**Comment by bytedance-tech** [comment]
已知问题， 最新版本已经修复此问题。
