### ISSUE TITLE
[BUG] iOS 16 闪退

### ISSUE THREAD

**Issue by flyingdandelion** [bytedance/Bytedance-UnionAD#161]
## Describe the bug | 问题描述
A clear and concise description of what the bug is. | 请简明清晰地描述你遇到的问题。

## Environmental information | 环境信息
 - SDK version: | SDK 版本： 4.7.0.8
 - Date and time: | 日期与时间： 任何时候
 - Device model: | 设备型号：任何手机
 - iOS version: | iOS 版本： iOS16 beta 8

## To Reproduce | Xcode 14 beta 6 + iOS 16 beta  随便loadAdData 都会出现
Steps to reproduce the behavior. |  只要调用广告加载就复现

提工单说是beta 版本不支持，iOS16 都要发布了，已经这么所人反馈了，难道你们都不解决吗？
实在是，唉。。。

**Comment by flyingdandelion** [comment]
实在解决不了，你们返回无广告也好呀，不要闪退
闪退了，app都打不开
开屏，信息流，激励视频，banner广告，全部崩溃，
6月底就反馈了，现在9月份，还是如此。。。。。

**Comment by nne998** [comment]
iOS 16 rc 出来了，希望官方快点解决。。

**Comment by TangBaoo** [comment]
确实还有问题 不修复新xcode都没法用

**Comment by nne998** [comment]
> 确实还有问题 不修复新xcode都没法用

我今天试过，更新pod到  4.7.1.1 就不闪退了

**Comment by HCongByte** [comment]
问题已解决，请更新Ads-CN，版本4.7.1.1或4.8.0.3
