### ISSUE TITLE
[BUG] CoreLocation - This method can cause UI unresponsiveness 

### ISSUE THREAD

**Issue by liudhzhyym** [bytedance/Bytedance-UnionAD#166]
## Describe the bug | 问题描述
SDK初始化的时候，xcode提示  warning run: This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.

## Environmental information | 环境信息
 - SDK version: | SDK 版本： Ads-CN-Beta 4.8.0.4
 - Date and time: | 日期与时间： 2022-10-05 21:00
 - Device model: | 设备型号： iPhone 12 Pro Max
 - iOS version: | iOS 版本： iOS16

## To Reproduce | 如何复现

初始化GroMore ABUAdSDKManager.setupSDK的时候，xcode提示警告

## Screenshots | 截图

<img width="2044" alt="image" src="https://user-images.githubusercontent.com/5382915/194091797-ec0e6fa3-9808-475f-979b-78a968b7e379.png">

**Comment by HCongByte** [comment]
GroMore 初始化警告问题已修复，请升级GroMore SDK版本
