### ISSUE TITLE
[BUG] Demo App 无法编译运行

### ISSUE THREAD

**Issue by prncoprs** [bytedance/Bytedance-UnionAD#192]
## Describe the bug | 问题描述
International Demo App 无法编译运行。错误信息如下：

`/Users/xxx/Bytedance-UnionAD/Demo/InternationalDemo/Objective-C/BUDemo/App/Until/Animation/BUDAnimationTool.h:9:9 'BUAdSDK/BUAdSDK.h' file not found`

## Environmental information | 环境信息
 - SDK name: | Ads-Global 
 - SDK version: | 5.1.0.7
 - Date and time: | 2023-05-04
 - Device model: | iPhone XsMax
 - iOS version: | iOS 14.8

## To Reproduce | 如何复现
`git clone`, `cd` to the directory, and `pod install`, 使用Xcode打开wcworkspace文件，修改签名为自己的developer account，compile，就会出现这种情况。

**Comment by zry-bd** [comment]
Thank you for your feedback. We have fixed this bug in version 5.1.1.0. Please update to the latest version or download the demo from the official website.
谢谢你的反馈。我们已经在5.1.1.0版本修复了该问题，请更新到最新版本或到官网下载Demo。
