### ISSUE TITLE
Unity导出的iOS工程集成出错

### ISSUE THREAD

**Issue by BakerInGit** [bytedance/Bytedance-UnionAD#2]
![image](https://user-images.githubusercontent.com/9129860/54818049-55a1fa80-4cd3-11e9-9c6f-91732f8d2907.png)
这是出错的地方
我的工程环境：Xcode：Version 10.1 (10B61) 
电脑：Mac Pro。
Unity导出的iOS工程 ，Unity：2018.2.3f1版本 这个项目很简单，就几个按钮，
我的iOS工程配置截图：
![image](https://user-images.githubusercontent.com/9129860/54818524-6ef77680-4cd4-11e9-824a-62c6f7c47330.png)
![image](https://user-images.githubusercontent.com/9129860/54818561-86366400-4cd4-11e9-9679-b53746a52393.png)
![1553252501848](https://user-images.githubusercontent.com/9129860/54818858-373cfe80-4cd5-11e9-9281-02fd031268f7.jpg)
![1553252521324](https://user-images.githubusercontent.com/9129860/54818867-3c01b280-4cd5-11e9-98d3-d1b6c22bcf4e.jpg)
![1553252538113](https://user-images.githubusercontent.com/9129860/54818873-3f953980-4cd5-11e9-857d-9f5ef4a8b6b4.jpg)
![1553252560427](https://user-images.githubusercontent.com/9129860/54818876-4328c080-4cd5-11e9-9aea-3fa5bdd21e43.jpg)

**Comment by BakerInGit** [comment]
搞定了。缺少frame ImageIO
![image](https://user-images.githubusercontent.com/9129860/54824198-2c8a6580-4ce5-11e9-9db5-dcafe982c18a.png)
你们竟然没有说需要~~！

**Comment by yh980237697** [comment]
抱歉，之前没有对unity进行支持，imageIO在iOS工程下是不需要单独链接的。建议您后面可以关注下穿山甲可提供unity插件形式，具体可通过商务渠道了解
