### ISSUE TITLE
pod 一直安装不了

### ISSUE THREAD

**Issue by pengshuangta** [bytedance/Bytedance-UnionAD#20]
你们这个库是不是很大啊，pod安装一直安装不了，过了很久之后直接提示hung up，同样是做广告平台的sdk，腾讯的广点通很快就安装好了。

**Comment by Li-Yudong** [comment]
就是安装不了，不知道咋解决

**Comment by yaofeijian** [comment]
我也有此类现象，有人解答下吗

**Comment by yh980237697** [comment]
有同学解决了，请参考下https://www.cnblogs.com/zjfjava/p/10392150.html
