### ISSUE TITLE
[BUG] DomesticDemo xcode 15.3运行报错

### ISSUE THREAD

**Issue by xiaoosnggao** [bytedance/Bytedance-UnionAD#204]
## Describe the bug | 问题描述
A clear and concise description of what the bug is. | 请简明清晰地描述你遇到的问题。

[DomesticDemo](https://github.com/bytedance/Bytedance-UnionAD/tree/master/Demo/DomesticDemo)
运行报错
![image](https://github.com/bytedance/Bytedance-UnionAD/assets/16183057/f45ec514-b272-4877-8ea6-c5e18495495d)
![image](https://github.com/bytedance/Bytedance-UnionAD/assets/16183057/626acc9b-b34c-4516-ae00-8b6b0ea3bf90)

## Environmental information | 环境信息
 - SDK name: | SDK 名称： Ads-CN
 - SDK version: | SDK 版本： 6.0.1.2
 - Date and time: | 日期与时间： 2024-04-19 16:02
 - Device model: | 设备型号：xcode 模拟器
 - iOS version: | iOS 版本： 17.2

## To Reproduce | 如何复现
Steps to reproduce the behavior. | 如果可以的话，请描述如何复现这个问题。

## Screenshots | 截图
If applicable, add screenshots to help explain your problem. | 如果有必要，请在这里粘贴问题相关的截图。

## Backtrace | 相关堆栈
Please paste the backtrace related to the Bug. | 如果可以的话，请在这里粘贴问题相关的堆栈信息（已符号化、可读）。

## Additional context | 附言
Add any other context about the problem here. | 请留下你认为可以帮助解决这个问题的任何信息。

**Comment by Leo008** [comment]
same + 1 in Xcode 15.1, macbook pro m1
<img width="1512" alt="截屏2024-04-26 10 27 01" src="https://github.com/bytedance/Bytedance-UnionAD/assets/14030737/1121d386-d171-46d0-b94a-946ead08f912">

**Comment by HCongByte** [comment]
感谢反馈！BURewardedVideoAdDelegate相关API已经下掉，上述问题已经在6.1.1.0版本修复，可以更新到最新版本。
