### ISSUE TITLE
Installing Bytedance-UnionAD (2.4.6.7)等待很久之后，还是无法安装成功，换了其他版本也是这样，无非安装，是否能尽快回复一下呢

### ISSUE THREAD

**Issue by pengshuangta** [bytedance/Bytedance-UnionAD#21]
[!] Error installing Bytedance-UnionAD
[!] /usr/bin/git clone https://github.com/bytedance/Bytedance-UnionAD.git /var/folders/yg/rczw4kln29xd_76zy1p4yk100000gn/T/d20191008-22549-nsfj87 --template= --single-branch --depth 1 --branch 2.4.6.7

Cloning into '/var/folders/yg/rczw4kln29xd_76zy1p4yk100000gn/T/d20191008-22549-nsfj87'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by mcheng315** [comment]
翻墙可以安装成功

**Comment by pengshuangta** [comment]
> 翻墙可以安装成功

在pod的过程，我查看了下载的进度，是有在下载的，但是包貌似比较大，服务器会经常的hung up，后面经过多次的尝试，终于pod成功了。

**Comment by ChristingLi** [comment]
给你的git配置上代理就OK了，一样是从git上下载文件
