### ISSUE TITLE
-canOpenURL: failed for URL: "bytedance://private/setresult/SCENE_FETCHQUEUE&W3siSlNTREsiOjEsImZ1bmMiOiJhZEluZm8iLCJwYXJhbXMiOnt9LCJfX21zZ190eXBlIjoiY2FsbCIsIl9fY2FsbGJhY2tfaWQiOiIxMDAwIiwiX190cyI6MTU3MDc4MjAzMTY0Nn1d" - error: "This app is not allowed to query for scheme bytedance"

### ISSUE THREAD

**Issue by yuanzhiying** [bytedance/Bytedance-UnionAD#22]
iOS13.1.2播放激励视频之后，出现如下：
-canOpenURL: failed for URL: "bytedance://private/setresult/SCENE_FETCHQUEUE&W3siSlNTREsiOjEsImZ1bmMiOiJhZEluZm8iLCJwYXJhbXMiOnt9LCJfX21zZ190eXBlIjoiY2FsbCIsIl9fY2FsbGJhY2tfaWQiOiIxMDAwIiwiX190cyI6MTU3MDc4MjAzMTY0Nn1d" - error: "This app is not allowed to query for scheme bytedance"

**Comment by cuiyanan02** [comment]
是正常log，不影响使用哦
