### ISSUE TITLE
banner View 代码位跟前端高度对应不上。

### ISSUE THREAD

**Issue by williamlv** [bytedance/Bytedance-UnionAD#27]
CGFloat screenWidth = CGRectGetWidth([UIScreen mainScreen].bounds);
        CGFloat bannerHeigh = screenWidth/600*90;
        BUSize *imgSize = [BUSize sizeBy:BUProposalSize_Banner600_150];
        self.bannerView = [[BUNativeExpressBannerView alloc] initWithSlotID:self.viewModel.slotID rootViewController:self imgSize:imgSize adSize:CGSizeMake(screenWidth, bannerHeigh) IsSupportDeepLink:YES];
        self.bannerView.frame = CGRectMake(0, 10, screenWidth, bannerHeigh);
        self.bannerView.delegate = self;
        [self.view addSubview:self.bannerView];
这是官方例子。
后台设置的代码位600*150，为什么前端只能screenWidth/600*90才正好显示。如果也显示150，上下会有很大空白。
前端想显示150高度，后台有哪个高度的代码位？

**Comment by yh980237697** [comment]
请到媒体平台的留言反馈中，找到技术问题留言。直接提工单，有专业的同学回复。
