### ISSUE TITLE
BUNativeExpresInterstitialAdDelegate中的DidClick代理不会调出来

### ISSUE THREAD

**Issue by eroscai** [bytedance/Bytedance-UnionAD#28]
使用环境：Swift
使用版本：2.5.1.2
问题说明：
当正常加载并展示广告以后，点击任何区域应该是要触发nativeExpresInterstitialAdDidClick代理才对。但是目前测试看会直接调用nativeExpresInterstitialAdDidClose这个代理。
其余展示这种代理是正常调用的，希望尽快查一下，这个应该跟Swift或者OC环境无关，应该是哪一块逻辑漏掉了吧？

**Comment by yh980237697** [comment]
目前还没有发现这个，请参考下BUDemo，是否存在则个问题，如果没有解决可以升级SDK或者，提供下接入demo
