### ISSUE TITLE
视频广告部分情况阻塞主线程的问题

### ISSUE THREAD

**Issue by suochenhe** [bytedance/Bytedance-UnionAD#3]
BUDFeedVideoAdTableViewCell.(BUNativeAdRelatedView*)nativeAdRelatedView.(BUVideoAdView *)videoAdView 加载视频的时候，公司wifi环境不是很好也不是很差，会经常出现卡住主线程的情况。
触发场景：下拉刷新请求数据后，如果视频广告直接展示在屏幕上，会比较大概率出现阻塞主线程的情况，此时refreshView不能回弹，页面不能操作；之后不再阻塞主线程，往往视频广告播放器上提示  视频加载失败请重试

**Comment by yh980237697** [comment]
请更新到>=V2202版本
