### ISSUE TITLE
App gets terminated in background with an assertion (0x8badf00d)

### ISSUE THREAD

**Issue by KorolZhu** [bytedance/Bytedance-UnionAD#31]
app退后台几分钟就被杀了，再进前台就看到启动画面了。最近加了这个这个sdk，猜测有没有可能影响。有其他人碰到过吗。

和下面这两个个问题是一样的
https://forums.developer.apple.com/thread/85018
https://github.com/Instabug/Instabug-iOS/issues/305

**Comment by KorolZhu** [comment]
我去掉Bytedance-UnionAD sdk确实正常了，麻烦作者可以查下这个问题吗。

**Comment by yh980237697** [comment]
>=V2.5.1.0的版本解决了这个问题
