### ISSUE TITLE
2.5.1.5 初始化遇到 crash 

### ISSUE THREAD

**Issue by MrYulong** [bytedance/Bytedance-UnionAD#34]
SDK 版本： 2.5.1.5
手机版本：iPhone 7 Plus，iOS 12.4.1

启动时遇到连续 crash ，麻烦排查，谢谢。

+[BUOpenUDID valueWithError:] + 768
-[BUDevice loadCurrentAppInfo] + 128
+[BUDevice currentDevice] + 56
-[BUUSettingService buildupService] + 40
+[BUUSettingService service] + 56
+[BUAdSDKManager setAppID:] + 288

**Comment by yh980237697** [comment]
三方库OpenUDID的问题，在2800版本会去掉openudid，请及时关注
