### ISSUE TITLE
2.5.1.5激励视频点击后卡死冻屏

### ISSUE THREAD

**Issue by xurigan** [bytedance/Bytedance-UnionAD#35]
1.激励视频播放中,点击激励视频:打印
viewWillAppear: <SKStoreProductViewController: 0x157d8e560>
viewWillAppear: <UIInputWindowController: 0x15b051c00>
viewWillAppear: <SKRemoteProductViewController: 0x158094600>
2.关闭Appstore的页面:打印
[Application] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
3.视频暂停  卡死  无法继续播放  无法退出  只能杀死应用重启,  GDT家的并没有此问题

**Comment by iceYou123** [comment]
同问。2.7版本就没这个问题

**Comment by yh980237697** [comment]
请升级版本看是否解决，如没有解决请联系媒体平台到留言反馈中，找到技术问题留言，直接提工单吧，有专业的同学回复
