### ISSUE TITLE
2.5.1.5 初始化SDK遇到崩溃

### ISSUE THREAD

**Issue by documentzhou** [bytedance/Bytedance-UnionAD#37]
模拟器iPhoneX、iPhoneXr、iPhoneXs、iPhoneXs Max，12.4崩溃，iPhone11 13.2.2则不崩溃其余未测试
真机iPhoneXs 12.4崩溃，iPhone6 11.4未崩溃，其余未测试
麻烦尽快排查修复，之前用的2.4.6.7，未出现崩溃现象

**Comment by mouse-lin** [comment]
同样，12.x 系统都会奔溃，13.x 以上就不会

**Comment by yh980237697** [comment]
有崩溃日志吗

**Comment by yh980237697** [comment]
即将发布版本来解决，感谢反馈
