### ISSUE TITLE
pod 2.7.5.2 失败

### ISSUE THREAD

**Issue by Juefeiye** [bytedance/Bytedance-UnionAD#41]
Installing Bytedance-UnionAD (2.7.5.2)

[!] Error installing Bytedance-UnionAD
[!] /usr/local/bin/git clone https://github.com/bytedance/Bytedance-UnionAD.git /var/folders/gb/1k95p0js7nd29td1066h608r0000gn/T/d20200102-4217-lg3pjq --template= --single-branch --depth 1 --branch 2.7.5.2

Cloning into '/var/folders/gb/1k95p0js7nd29td1066h608r0000gn/T/d20200102-4217-lg3pjq'...
Note: checking out '1d1206705f631fac08309b5cbb3ad989ffd9df8f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

git-lfs filter-process: git-lfs: command not found
fatal: The remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by cuiyanan02** [comment]
麻烦看一下readme，安装一下LFS服务
