### ISSUE TITLE
pod 2.7.5.2的架构问题

### ISSUE THREAD

**Issue by guolimin1995** [bytedance/Bytedance-UnionAD#42]
Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_BURewardedVideoAd", referenced from:
          objc-class-ref in libshuiyun_ios.a(BUAdRewardedVideo.o)
      "_OBJC_CLASS_$_BURewardedVideoModel", referenced from:
          objc-class-ref in libshuiyun_ios.a(BUAdRewardedVideo.o)
      "_OBJC_CLASS_$_BUAdSDKManager", referenced from:
          objc-class-ref in libshuiyun_ios.a(SYSdkUtils.o)
      "_OBJC_CLASS_$_BUNativeExpressBannerView", referenced from:
          objc-class-ref in libshuiyun_ios.a(BUAdBanner.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbols for architecture i386:
      "_OBJC_CLASS_$_BURewardedVideoAd", referenced from:
          objc-class-ref in libshuiyun_ios.a(BUAdRewardedVideo.o)

显示这个几个文件引用不支持此架构，我的代码在老一个版本是可以的，新的有这个报错，请问是什么问题呢

**Comment by cuiyanan02** [comment]
新版本不再支持i386架构了

**Comment by guolimin1995** [comment]
> 新版本不再支持i386架构了

那x86_64呢

**Comment by guolimin1995** [comment]
> 新版本不再支持i386架构了

你好

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_BURewardedVideoAd", referenced from:
      objc-class-ref in libshuiyun_ios.a(BUAdRewardedVideo.o)
  "_OBJC_CLASS_$_BURewardedVideoModel", referenced from:
      objc-class-ref in libshuiyun_ios.a(BUAdRewardedVideo.o)
  "_OBJC_CLASS_$_BUAdSDKManager", referenced from:
      objc-class-ref in libshuiyun_ios.a(SYSdkUtils.o)
  "_OBJC_CLASS_$_BUNativeExpressBannerView", referenced from:
      objc-class-ref in libshuiyun_ios.a(BUAdBanner.o)
ld: symbol(s) not found for architecture arm64

这个编译报错是 arm64架构错误

**Comment by cuiyanan02** [comment]
麻烦看一下readme，先安装LFS服务再pod install,如果已经pod install过了，请先清除pod 本地缓存，再从服务端重新拉取

**Comment by guolimin1995** [comment]
> 麻烦看一下readme，先安装LFS服务再pod install,如果已经pod install过了，请先清除pod 本地缓存，再从服务端重新拉取

 好的，谢谢哈

**Comment by devyu** [comment]
@guolimin1995 请问你解决这个问题了吗，尝试安装了LFS服务，然后清除pod缓存，仍然是x86_64错误
