### ISSUE TITLE
2.7.5.2编译出错

### ISSUE THREAD

**Issue by hjz20089** [bytedance/Bytedance-UnionAD#43]
架构问题，2.5.1.5没问题

**Comment by cuiyanan02** [comment]
新版本不再支持i386架构了，辛苦看一下readme的提示

**Comment by guolimin1995** [comment]
> 新版本不再支持i386架构了，辛苦看一下readme的提示

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_BURewardedVideoAd", referenced from:
      objc-class-ref in libshuiyun_ios.a(BUAdRewardedVideo.o)
  "_OBJC_CLASS_$_BURewardedVideoModel", referenced from:
      objc-class-ref in libshuiyun_ios.a(BUAdRewardedVideo.o)
  "_OBJC_CLASS_$_BUAdSDKManager", referenced from:
      objc-class-ref in libshuiyun_ios.a(SYSdkUtils.o)
  "_OBJC_CLASS_$_BUNativeExpressBannerView", referenced from:
      objc-class-ref in libshuiyun_ios.a(BUAdBanner.o)
ld: symbol(s) not found for architecture arm64

我的也是这个问题 arm64的

**Comment by cuiyanan02** [comment]
> > 新版本不再支持i386架构了，辛苦看一下readme的提示
> 
> Undefined symbols for architecture arm64:
> "_OBJC_CLASS_$_BURewardedVideoAd", referenced from:
> objc-class-ref in libshuiyun_ios.a(BUAdRewardedVideo.o)
> "_OBJC_CLASS_$_BURewardedVideoModel", referenced from:
> objc-class-ref in libshuiyun_ios.a(BUAdRewardedVideo.o)
> "_OBJC_CLASS_$_BUAdSDKManager", referenced from:
> objc-class-ref in libshuiyun_ios.a(SYSdkUtils.o)
> "_OBJC_CLASS_$_BUNativeExpressBannerView", referenced from:
> objc-class-ref in libshuiyun_ios.a(BUAdBanner.o)
> ld: symbol(s) not found for architecture arm64
> 
> 我的也是这个问题 arm64的

请先安装LFS服务再pod install，已经pod install过的请先清除pod的本地缓存，再重新pod
