### ISSUE TITLE
Error installing Bytedance-UnionAD

### ISSUE THREAD

**Issue by liuyasss** [bytedance/Bytedance-UnionAD#44]
$ pod install
Analyzing dependencies
Pre-downloading: `Weibo_SDK` from `https://github.com/sinaweibosdk/weibo_ios_sdk.git`, commit `593a51c8f83e3afbc533b030e391d1f273daadfb`
Downloading dependencies
Installing AppsFlyerFramework 5.1.0 (was 4.11.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing Bugly 2.5.2 (was 2.5.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing Bytedance-UnionAD 2.7.5.2 (was 2.4.6.7 and source changed to `https://cdn.cocoapods.org/` from `trunk`)

[!] Error installing Bytedance-UnionAD
[!] /usr/local/bin/git clone https://github.com/bytedance/Bytedance-UnionAD.git /var/folders/lp/09n8dp_j3kq48y_v1jz649880000gn/T/d20200110-40907-1e1g5bf --template= --single-branch --depth 1 --branch 2.7.5.2

Cloning into '/var/folders/lp/09n8dp_j3kq48y_v1jz649880000gn/T/d20200110-40907-1e1g5bf'...
Note: switching to '1d1206705f631fac08309b5cbb3ad989ffd9df8f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by WXinYi** [comment]
这个问题我也碰到了， 重新安装了git-lfs 后OK了。如果有brew的话执行 brew install git-lfs 即可，没有的话https://git-lfs.github.com/  在官网找找。
