### ISSUE TITLE
是不是不支持模拟器啊, 编译直接报错了

### ISSUE THREAD

**Issue by ZexiFangkong** [bytedance/Bytedance-UnionAD#47]
看官网显示支持 
![image](https://user-images.githubusercontent.com/23274725/74219466-e157b780-4ce7-11ea-8f00-83a10c0ccd2d.png)

Version 11.3.1 (11C504)
iPhone 11 编译报错
![image](https://user-images.githubusercontent.com/23274725/74219523-02b8a380-4ce8-11ea-9992-3351e267847d.png)

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BUSplashAdView", referenced from:
      objc-class-ref in 530.x86_64.thinlto.o
  "_OBJC_CLASS_$_BUSize", referenced from:
      objc-class-ref in PangolinADManager.o
  "_OBJC_CLASS_$_BUImage", referenced from:
      objc-class-ref in AdDataProtocol.o
  "_OBJC_CLASS_$_BUNativeAdsManager", referenced from:
      objc-class-ref in PangolinADManager.o
  "_OBJC_CLASS_$_BUAdSDKManager", referenced from:
      objc-class-ref in AdManager.o
  "_OBJC_CLASS_$_BUAdSlot", referenced from:
      objc-class-ref in PangolinADManager.o
  "_OBJC_CLASS_$_BUVideoAdView", referenced from:
      objc-class-ref in OpenScreenBaiduADView.o
  "_OBJC_CLASS_$_BUNativeAd", referenced from:
      l__CATEGORY_BUNativeAd_$_HelloTalk_Binary in AdDataProtocol.o
      objc-class-ref in OpenScreenBaiduADView.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by AlanMoMo** [comment]
我也遇到了同样的问题

**Comment by ZexiFangkong** [comment]
> 我也遇到了同样的问题

不知道是官网没更新, 还是兼容没做好

**Comment by yh980237697** [comment]
应该是缺少BUFoundation.framework库导致的，我在手动导入环境不引入这个库和pod导入报错一致，导入后报错消除。
