### ISSUE TITLE
真机编译报错

### ISSUE THREAD

**Issue by ZexiFangkong** [bytedance/Bytedance-UnionAD#48]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_BUSplashAdView", referenced from:
      objc-class-ref in 530.arm64.thinlto.o
  "_OBJC_CLASS_$_BUSize", referenced from:
      objc-class-ref in PangolinADManager.o
  "_OBJC_CLASS_$_BUImage", referenced from:
      objc-class-ref in AdDataProtocol.o
  "_OBJC_CLASS_$_BUNativeAdsManager", referenced from:
      objc-class-ref in PangolinADManager.o
  "_OBJC_CLASS_$_BUAdSDKManager", referenced from:
      objc-class-ref in AdManager.o
  "_OBJC_CLASS_$_BUAdSlot", referenced from:
      objc-class-ref in PangolinADManager.o
  "_OBJC_CLASS_$_BUVideoAdView", referenced from:
      objc-class-ref in OpenScreenBaiduADView.o
  "_OBJC_CLASS_$_BUNativeAd", referenced from:
      l__CATEGORY_BUNativeAd_$_HelloTalk_Binary in AdDataProtocol.o
      objc-class-ref in OpenScreenBaiduADView.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by 740629515** [comment]
我也遇到了同样的问题

**Comment by jacoli** [comment]
遇到同样链接问题

**Comment by CocodingLee** [comment]
你们他妈真实狗， 也是个大长。 demo都搞的符号不完整。

**Comment by AmadeusSys** [comment]
同样的问题

**Comment by AmadeusSys** [comment]
经过我手动导入测试 ，应该是缺少BUFoundation.framework库导致的，我在手动导入环境不引入这个库和pod导入报错一致，导入后报错消除。
