### ISSUE TITLE
iPhone XR 读取开屏广告卡主线程

### ISSUE THREAD

**Issue by FatDogJOE** [bytedance/Bytedance-UnionAD#5]
iPhone XR(12.3.1)读取开屏广告会卡很久。 控制台还会打印如下错误。
![屏幕快照 2019-06-17 上午11 59 36](https://user-images.githubusercontent.com/44893843/59577726-796cb500-90f7-11e9-82d1-6a58afb60b31.png)

**Comment by yh980237697** [comment]
请升级最新按本
