### ISSUE TITLE
有没有确定的系统支持版本

### ISSUE THREAD

**Issue by Feng-xp** [bytedance/Bytedance-UnionAD#50]
我看iOS文档写运行配置支持 iOS9.x 以上，xcode11 编译，但是 podspec 文件里的最低版本是 iOS8.0

那么最新 SDK 到底从哪个版本开始支持，是否必须要用xcode11 编译

**Comment by yh980237697** [comment]
抱歉 请以接入文档为准，支持 iOS9.x 以上，xcode11 编译。podspec回头我们改一下 iOS 9
