### ISSUE TITLE
大量崩溃

### ISSUE THREAD

**Issue by uzhy1987** [bytedance/Bytedance-UnionAD#52]
0 WebKit | WTFCrashWithInfo(int, char const*, char const*, int) + 20
-- | --
1 WebKit | WebKit::WebProcessProxy::~WebProcessProxy() + 952
2 WebKit | WebKit::WebProcessProxy::~WebProcessProxy() + 12
3 WebKit | WebKit::WebURLSchemeTask::~WebURLSchemeTask() + 156
4 WebKit | WTF::RefCounted<WebKit::WebURLSchemeTask>::deref() const + 32
5 WebKit | -[WKURLSchemeTaskImpl dealloc] + 60
6 libsystem_blocks.dylib | _Block_release + 152
7 App名称 | ___destroy_helper_block_.186 + 40
8 libsystem_blocks.dylib | _Block_release + 152
9 CoreFoundation | -[__NSSingleObjectArrayI dealloc] + 44
10 libobjc.A.dylib | (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 672
11 App名称 | ___73-[BU_SDWebImageDownloaderOperation URLSession:task:didCompleteWithError:]_block_invoke.219 + 520
12 libdispatch.dylib | __dispatch_call_block_and_release + 24

**Comment by Ryan007008** [comment]
遇到相同问题，都发生在iOS 12 上面

**Comment by DreamChaserEric** [comment]
我也遇到了类似的问题，调用栈不完全一样，1-9行是一样的。
我也都发生在iOS 12，使用版本是灰度中的2.9.x，单这一个crash，crash率超过1%
我现在尝试回退版本了，效果还没观察到

**Comment by hongfeiqianli** [comment]
遇到相同问题，都发生在iOS 12 上面，使用版本2.7.5。从堆栈分析来看很大可能web多线程问题。希望尽快解决吧

**Comment by zfpan1981** [comment]
有解决吗

**Comment by yh980237697** [comment]
3000版本进行修复，请关注，感谢反馈

**Comment by billxie1988** [comment]
Keep WKURLSchemeTaskImpl dealloc in main thread

**Comment by zhangdongpo** [comment]
> WKURLSchemeTaskImpl

How to keep dealloc in main thread?

**Comment by billxie1988** [comment]
通过对最新版本webkit源码核对，最新版本源码中在dealloc时会将析构过程放入主线程中

**Comment by EvanTree** [comment]
这个崩溃具体在哪个版本解决的？有人回复一下吗

**Comment by EvanTree** [comment]
这个崩溃具体在哪个版本解决的？我看版本3.0.0.2上还是会出现这个崩溃。有人回复一下吗？

**Comment by denglei022** [comment]
> 通过对最新版本webkit源码核对，最新版本源码中在dealloc时会将析构过程放入主线程中

这个问题怎么解决，不是很明白，我现在用普通的wkwebview在ios12上也会碰到这个崩溃

**Comment by uzhy1987** [comment]
3.0以上版本还是会崩溃    我看苹果官方说的解决方案是https://developer.apple.com/forums/thread/112574

**Comment by kai60** [comment]
> 通过对最新版本webkit源码核对，最新版本源码中在dealloc时会将析构过程放入主线程中

兄弟，我没有使用这个sdk,但是在使用WKURLSchemeHandler也碰到这个问题，大佬有方案么

**Comment by SuomiKP31** [comment]
> > 通过对最新版本webkit源码核对，最新版本源码中在dealloc时会将析构过程放入主线程中
> 
> 兄弟，我没有使用这个sdk,但是在使用WKURLSchemeHandler也碰到这个问题，大佬有方案么

触发原理，Webview进行跨站导航时，会创建新的webview进程，加载完成后再销毁原进程。
原进程的析构有概率不在主线程，若不在则触发此崩溃。
解决的办法，尝试将析构放回主线程或者实现非异步的Navigation Action协议
