### ISSUE TITLE
_OBJC_CLASS_$_BUAdSDKManager

### ISSUE THREAD

**Issue by CarsonChen0312** [bytedance/Bytedance-UnionAD#53]
Swift工程中，Pod 导入 2.8.0.1 编译正常，但是一初始化SDK IDE报错
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BUAdSDKManager", referenced from:
      objc-class-ref in AppDelegate.o

**Comment by enamor** [comment]
遇到了同样的问题

**Comment by enamor** [comment]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_BUAdSDKManager", referenced from:
      objc-class-ref in AppDelegate.o

**Comment by zanyzephyr** [comment]
遇到了同样的问题：
![image](https://user-images.githubusercontent.com/23650458/75737426-aa028680-5d3a-11ea-8b36-4775518f245a.png)

**另外：**
1.Macbook pro上没问题。没有对Pods文件夹做版本控制，在Mac mini上，pods安装后，就有问题了
2.如果把整个工程文件夹，整个复制到Mac mini上，而不是通过pods安装，也没有问题。
（可能是哪里的配置文件不一样吧，但是没有发现哪里不一样）

**环境：**
macOS 10.15.3
Xcode 11.3.1

**Comment by ZHANGYAOJIANG** [comment]
你们解决了这个问题了吗

**Comment by Nitch97** [comment]
同样的问题, 尝试了各种方法目前还不能解决

**Comment by danleechina** [comment]
首先要安装 LFS，然后 pod install。 还有问题的话，有可能是 Cocoapods 的缓存，执行这个命令`rm -rf  ~/Library/Caches/CocoaPods`，重新 pod install 就可以了。

**Comment by Nitch97** [comment]
> 首先要安装 LFS，然后 pod install。 还有问题的话，有可能是 Cocoapods 的缓存，执行这个命令`rm -rf ~/Library/Caches/CocoaPods`，重新 pod install 就可以了。

实测有效 刚刚在穿山甲官网https://partner.oceanengine.com/union/media/union/download/log?id=1 找到了2752版本的说明 对于老版本更新上来, 真的是一脸懵逼了

**Comment by ZHANGYAOJIANG** [comment]
已经解决了 楼上说的正解 可能缓存引起的

**Comment by zanyzephyr** [comment]
> 首先要安装 LFS，然后 pod install。 还有问题的话，有可能是 Cocoapods 的缓存，执行这个命令`rm -rf ~/Library/Caches/CocoaPods`，重新 pod install 就可以了。

清除Cocoapods缓存后解决了，感谢

**Comment by zh20102618** [comment]
按照这个方法操作了还是不行，而且手动直接导入工程集成，也是报同样的错误，电脑mac mini 10.14.5

**Comment by AmadeusSys** [comment]
经过我手动导入测试 ，应该是缺少BUFoundation.framework库导致的，我在手动导入环境不引入这个库和pod导入报错一致，导入后报错消除。

**Comment by yh980237697** [comment]
已解决，closed
