### ISSUE TITLE
building for iOS-arm64 but attempting to link with file built for unknown-unsupported file format

### ISSUE THREAD

**Issue by avalon451990** [bytedance/Bytedance-UnionAD#55]
2.8.0.1版本的BUAdSDK.framework的架构无法识别
使用一下命令:
lipo -info BUAdSDK
得到的:
can't figure out the architecture type of: BUAdSDK

**Comment by KorolZhu** [comment]
升级到2.8.0.1，遇到相同的问题，直接编译不过

![image](https://user-images.githubusercontent.com/1926639/76817120-f79fe880-683c-11ea-9536-4accb2e19b07.png)

有解决方案吗

**Comment by binbins** [comment]
![image](https://user-images.githubusercontent.com/17695499/76939866-264cba80-6934-11ea-9a25-6f6204822ef5.png)
Xcode版本11.3，pod版本1.7.0.beta.3在使用2.8.0.1遇到同样的问题，

**Comment by binbins** [comment]
问题原因：似乎是少了BUFoundation.framework
![image](https://user-images.githubusercontent.com/17695499/76944739-7fb8e780-693c-11ea-830f-7ea908ff827a.png)

解决办法：改用手动导入sdk，我导了2.9.5.0 好了

**Comment by avalon451990** [comment]
楼上正解!!!
