### ISSUE TITLE
Why podspec contains this script line? It made our project rejected by App Store Connect.

### ISSUE THREAD

**Issue by danleechina** [bytedance/Bytedance-UnionAD#56]
https://github.com/bytedance/Bytedance-UnionAD/blob/34243474825fd31942d14e15805951b62b99eacc/Bytedance-UnionAD.podspec#L31

**Comment by yh980237697** [comment]
什么原因导致appstore过审失败？

**Comment by danleechina** [comment]
上传包的时候失败了，因为包含了 x86_64 的代码，被认为是非法二进制文件。
