### ISSUE TITLE
iphone5，iphone6跑游戏接广告频繁报渲染失败

### ISSUE THREAD

**Issue by liuyaqiang** [bytedance/Bytedance-UnionAD#58]
Error Domain=com.bytedance.buadsdk Code=107 "native Express ad, render timeout" UserInfo={NSLocalizedDescription=native Express ad, render timeout}

**Comment by DIVEINBLUE** [comment]
ipad air 2019 同样的问题，一直失败没成功过

**Comment by yh980237697** [comment]
接入 3105版本试试
