### ISSUE TITLE
xcode版本：11.4，机型：Ipad Air2，错误：Banner渲染失败107错误码

### ISSUE THREAD

**Issue by 1501432163** [bytedance/Bytedance-UnionAD#61]
xcode版本：11.4
机型：Ipad Air2
错误：Banner渲染失败107错误码
以下是失败Log：
![image](https://user-images.githubusercontent.com/12163502/78774416-3aca2300-79c7-11ea-95e4-4ffcb01f9e0f.png)
代码：
![image](https://user-images.githubusercontent.com/12163502/78774502-58978800-79c7-11ea-8c07-bb91b028d730.png)
--------------------------------------------------
麻烦看下，谢谢
补充：同样的代码，用iPhone运行没问题，会显示banner。

**Comment by 1501432163** [comment]
现在只有ipad有问题，渲染不出来

**Comment by 1501432163** [comment]
ipad的ios版本是13.4

**Comment by zhangxiangguang** [comment]
考虑设置下setIsPaidApp：方法

**Comment by 1501432163** [comment]
> 考虑设置下setIsPaidApp：方法

可以了，3q
