### ISSUE TITLE
pod lib lint error

### ISSUE THREAD

**Issue by Wyt0801** [bytedance/Bytedance-UnionAD#69]
![error](https://user-images.githubusercontent.com/32116828/79742068-dac36d00-8334-11ea-9a36-ef8c9ae36abb.png)
pod lib lint 错误，2.8.0.1版本可以通过

**Comment by yh980237697** [comment]
架构目前只支持'armv7', 'armv7s', 'x86_64', 'arm64'，暂不支持i386
