### ISSUE TITLE
pod failed

### ISSUE THREAD

**Issue by PengJiang520** [bytedance/Bytedance-UnionAD#70]
Installing Bytedance-UnionAD (1.0.0)

[!] Error installing Bytedance-UnionAD
[!] /usr/bin/git clone https://github.com/bytedance/Bytedance-UnionAD.git /var/folders/sv/x6xyl_b92xn54h7sl2vbkq2h0000gn/T/d20200503-25225-18605iq --template= --single-branch --depth 1 --branch 1.0.0

Cloning into '/var/folders/sv/x6xyl_b92xn54h7sl2vbkq2h0000gn/T/d20200503-25225-18605iq'...
warning: Could not find remote branch 1.0.0 to clone.
fatal: Remote branch 1.0.0 not found in upstream origin

**Comment by yh980237697** [comment]
请使用正确的版本号，1.0.0更换成需要使用的版本号即可
