### ISSUE TITLE
反馈一个SDK内的Bug，方法交换的crash

### ISSUE THREAD

**Issue by kinkenyuen** [bytedance/Bytedance-UnionAD#72]
<img width="1390" alt="Xnip2020-05-07_09-55-28" src="https://user-images.githubusercontent.com/41050490/81246002-09398b80-9049-11ea-9162-d424c48e58b0.png">

上图是你SDK内部对+[WKWebView handlesURLScheme:]做的方法交换，（BUWKWebViewClient继承WKWebView）。

查看交换方法的内部实现，如下

<img width="1273" alt="Xnip2020-05-07_09-59-07" src="https://user-images.githubusercontent.com/41050490/81246155-6b928c00-9049-11ea-83d5-c4311b2c23a9.png">

可以发现你SDK将+[BUWKWebViewClient bu_handlesURLScheme:]的IMP直接set到了WKWebView的handlesURLScheme:这个SEL内

因此待你SDK内做完这次方法交换后，外部再调用+[WKWebView handlesURLScheme:]，会出现找不到SEL的crash

<img width="1567" alt="Xnip2020-05-07_10-07-09" src="https://user-images.githubusercontent.com/41050490/81246569-87e2f880-904a-11ea-9846-6bc23bd9d46c.png">

<img width="869" alt="Xnip2020-05-07_10-08-02" src="https://user-images.githubusercontent.com/41050490/81246617-a6e18a80-904a-11ea-8993-7a25404a47fa.png">

当调用[WKWebView handlesURLScheme:]时，会走到上面bu_handlesURLScheme:的实现，然后参数如果是非@"http"和@"https"时，就会出现如下调用+[WKWebView bu_handlesURLScheme:],很显然bu_handlesURLScheme:这个SEL没有在WKWebView里，而是在你SDK内部类BUWKWebViewClient

**Comment by yh980237697** [comment]
3000版本已经解决
