### ISSUE TITLE
真机编译都不能通过

### ISSUE THREAD

**Issue by SongXing** [bytedance/Bytedance-UnionAD#73]
Undefined symbols for architecture armv7:
  "_res_9_ninit", referenced from:
      +[SGMDataAcquisitionUnit sgm_DNS] in BUFoundation(SGMDataAcquisitionUnit.o)
  "_res_9_ndestroy", referenced from:
      +[SGMDataAcquisitionUnit sgm_DNS] in BUFoundation(SGMDataAcquisitionUnit.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yh980237697** [comment]
按照接入文档检查下依赖的库




| |
yh980237697
邮箱：yh980237697@163.com
|

Signature is customized by Netease Mail Master

在2020年05月12日 15:23，SongXing 写道：

Closed #73.
