### ISSUE TITLE
激励视频播放完闪退sdk为最新版本

### ISSUE THREAD

**Issue by sensencoder** [bytedance/Bytedance-UnionAD#76]
*** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument
(null)
((
    0 CoreFoundation 0x00000001af838604 409609CD-8410-38E1-BA5D-BDED609D2018 + 1222148
    1 libobjc.A.dylib 0x00000001af55abcc objc_exception_throw + 56
    2 Foundation 0x00000001afaf3490 1A46239D-F2FC-34B6-95BC-9F38869F0C85 + 29840
    3 Foundation 0x00000001afb3c238 1A46239D-F2FC-34B6-95BC-9F38869F0C85 + 328248
    4 BoGuTongJinZhe 0x0000000101807234 -[BUVideoAdView resetVideoPLayer] + 796
    5 BoGuTongJinZhe 0x0000000101807450 -[BUVideoAdView setMaterialMeta:] + 384
    6 BoGuTongJinZhe 0x000000010180629c -[BUVideoAdView initWithMaterial:] + 200
    7 BoGuTongJinZhe 0x00000001018ab208 -[BUAppStoreDisplayInAppViewController createVideoView] + 100
    8 BoGuTongJinZhe 0x00000001018aa858 -[BUAppStoreDisplayInAppViewController buildUpView] + 44
    9 BoGuTongJinZhe 0x00000001018aa6c8 -[BUAppStoreDisplayInAppViewController viewDidLoad] + 160
    10 UIKitCore 0x00000001b329de08 3062FF32-2182-37A2-A5F9-B38F6FB6B8C3 + 4091400
    11 UIKitCore 0x00000001b32a2898 3062FF32-2182-37A2-A5F9-B38F6FB6B8C3 + 4110488
    12 UIKitCore 0x00000001b32a2ca0 3062FF32-2182-37A2-A5F9-B38F6FB6B8C3 + 4111520
    13 UIKitCore 0x00000001b31cdccc 3062FF32-2182-37A2-A5F9-B38F6FB6B8C3 + 3239116
    14 UIKitCore 0x00000001b31c1810 3062FF32-2182-37A2-A5F9-B38F6FB6B8C3 + 3188752
    15 UIKitCore 0x00000001b32b24bc 3062FF32-2182-37A2-A5F9-B38F6FB6B8C3 + 4175036
    16 UIKitCore 0x00000001b32b5014 3062FF32-2182-37A2-A5F9-B38F6FB6B8C3 + 4186132
    17 UIKitCore 0x00000001b32b551c 3062FF32-2182-37A2-A5F9-B38F6FB6B8C3 + 4187420
    18 UIKitCore 0x00000001b32b4f64 3062FF32-2182-37A2-A5F9-B38F6FB6B8C3 + 4185956
    19 UIKitCore 0x00000001b32b51d0 3062FF32-2182-37A2-A5F9-B38F6FB6B8C3 + 4186576
    20 BoGuTongJinZhe 0x0000000101911c9c -[UIViewController(BUUtilities) bu_safelyPresentViewController:animated:completion:] + 120
    21 BoGuTongJinZhe 0x00000001019565e8 +[BURouter pushFromViewController:toViewController:] + 272
    22 BoGuTongJinZhe 0x00000001018950d8 -[BUVideoAdActionManager handleVideoAdActionWithModel:context:] + 340
    23 BoGuTongJinZhe 0x0000000101860090 -[BUAdActionManager BU_handleVideoAdActionWithModel:context:] + 168
    24 BoGuTongJinZhe 0x000000010181be70 -[BUNativeExpressFeedVideoAdView handleClickEventInvideo:] + 1040
    25 BoGuTongJinZhe 0x000000010184f194 -[BUNativeExpressAdView startHandleClickEventIsVideoClicked:isEndcardClicked:] + 304
    26 BoGuTongJinZhe 0x000000010184ef34 -[BUNativeExpressAdView handleClickEventIsVideoClicked:isEndcardClicked:] + 672
    27 BoGuTongJinZhe 0x000000010184bcb8 __43-[BUNativeExpressAdView registerClickEvent]_block_invoke + 428
    28 BoGuTongJinZhe 0x0000000101942c98 -[BUStaticPlugin callHandlerWithCommand:engine:completion:] + 496
    29 BoGuTongJinZhe 0x00000001019551c4 -[BUJSBForwarding forwardStaticPluginWithCommand:engine:completion:] + 124
    30 BoGuTongJinZhe 0x00000001019550a0 -[BUJSBForwarding forwardJSBWithCommand:engine:completion:] + 132
    31 BoGuTongJinZhe 0x000000010193ec04 __65+[BUWebViewApplication handleRequest:withWebView:viewController:]_block_invoke + 520
    32 BoGuTongJinZhe 0x0000000101925a78 __56-[BUWKWebView ttr_evaluateJavaScript:completionHandler:]_block_invoke + 52
    33 WebKit 0x00000001b6f22540 0D71FC8C-C7E3-3194-8094-D1C767C7BC09 + 1963328
    34 WebKit 0x00000001b6fc7520 0D71FC8C-C7E3-3194-8094-D1C767C7BC09 + 2639136
    35 WebKit 0x00000001b6fd1b24 0D71FC8C-C7E3-3194-8094-D1C767C7BC09 + 2681636
    36 WebKit 0x00000001b6fd18f4 0D71FC8C-C7E3-3194-8094-D1C767C7BC09 + 2681076
    37 WebKit 0x00000001b725951c 0D71FC8C-C7E3-3194-8094-D1C767C7BC09 + 5334300
    38 WebKit 0x00000001b724df50 0D71FC8C-C7E3-3194-8094-D1C767C7BC09 + 5287760
    39 WebKit 0x00000001b724af84 0D71FC8C-C7E3-3194-8094-D1C767C7BC09 + 5275524
    40 WebKit 0x00000001b6d85ae8 0D71FC8C-C7E3-3194-8094-D1C767C7BC09 + 273128
    41 WebKit 0x00000001b700b4d0 0D71FC8C-C7E3-3194-8094-D1C767C7BC09 + 2917584
    42 WebKit 0x00000001b6d73734 0D71FC8C-C7E3-3194-8094-D1C767C7BC09 + 198452
    43 WebKit 0x00000001b6d72d78 0D71FC8C-C7E3-3194-8094-D1C767C7BC09 + 195960
    44 JavaScriptCore 0x00000001be6d03dc AAF4E988-DFD3-3F50-AF21-779CF1258C80 + 230364
    45 JavaScriptCore 0x00000001be6d0578 AAF4E988-DFD3-3F50-AF21-779CF1258C80 + 230776
    46 CoreFoundation 0x00000001af7b6b64 409609CD-8410-38E1-BA5D-BDED609D2018 + 691044
    47 CoreFoundation 0x00000001af7b6abc 409609CD-8410-38E1-BA5D-BDED609D2018 + 690876
    48 CoreFoundation 0x00000001af7b6244 409609CD-8410-38E1-BA5D-BDED609D2018 + 688708
    49 CoreFoundation 0x00000001af7b1274 409609CD-8410-38E1-BA5D-BDED609D2018 + 668276
    50 CoreFoundation 0x00000001af7b0c34 CFRunLoopRunSpecific + 424
    51 GraphicsServices 0x00000001b98fa38c GSEventRunModal + 160
    52 UIKitCore 0x00000001b38e322c UIApplicationMain + 1932
    53 BoGuTongJinZhe 0x00000001015c21a0 main + 80
    54 libdyld.dylib 0x00000001af638800 876FB49A-BFBA-37BF-AD37-6FFC90F7F981 + 6144
)
dSYM UUID: 28C25520-5F23-3F59-AA28-2D0C77664E7E
CPU Type: arm64
Slide Address: 0x0000000100000000
Binary Image: BoGuTongJinZhe
Base Address: 0x0000000100fec000

**Comment by yh980237697** [comment]
3006版本修复，请接入最新版本
