### ISSUE TITLE
崩溃错误

### ISSUE THREAD

**Issue by jabez1314** [bytedance/Bytedance-UnionAD#79]
-[__NSCFString error]: unrecognized selector sent to instance 0x28019c780
(null)
((
    0 CoreFoundation 0x00000001849a0980 DC2C95C6-B954-39E8-86A2-5E0AF8801E87 + 1255808
    1 libobjc.A.dylib 0x00000001846b9028 objc_exception_throw + 60
    2 CoreFoundation 0x000000018489edcc DC2C95C6-B954-39E8-86A2-5E0AF8801E87 + 200140
    3 CoreFoundation 0x00000001849a5048 DC2C95C6-B954-39E8-86A2-5E0AF8801E87 + 1273928
    4 CoreFoundation 0x00000001849a73a0 _CF_forwarding_prep_0 + 96
    5 Foundation 0x0000000184c9b518 7A7A96AF-79E4-3DB1-8904-42E61CAE8999 + 296216
    6 App!-[BU_AFJSONResponseSerializer responseObjectForResponse:data:error:]
    7 App!-[BUNetworkAgent handleRequestResult:responseObject:error:]
    8 App!__121-[BUNetworkAgent dataTaskWithHTTPMethod:requestSerializer:URLString:httpBody:parameters:constructingBodyWithBlock:error:]_block_invoke
    9 App!__75-[BU_AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.104

**Comment by yh980237697** [comment]
V3200做了保护，请等待升级到后续版本使用
