### ISSUE TITLE
模拟器运行崩溃

### ISSUE THREAD

**Issue by GrandHahn** [bytedance/Bytedance-UnionAD#8]
你们官网文档和lipo -info都显示支持x86_64模拟器架构。但实际模拟器运行就崩溃，真机正常。版本:2201、2102。

**Comment by ZexiFangkong** [comment]
现在模拟器还能编译通过吗？ 我这边直接报错

**Comment by ZexiFangkong** [comment]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BUSplashAdView", referenced from:
      objc-class-ref in 530.x86_64.thinlto.o
  "_OBJC_CLASS_$_BUSize", referenced from:
      objc-class-ref in PangolinADManager.o
  "_OBJC_CLASS_$_BUImage", referenced from:
      objc-class-ref in AdDataProtocol.o
  "_OBJC_CLASS_$_BUNativeAdsManager", referenced from:
      objc-class-ref in PangolinADManager.o
  "_OBJC_CLASS_$_BUAdSDKManager", referenced from:
      objc-class-ref in AdManager.o
  "_OBJC_CLASS_$_BUAdSlot", referenced from:
      objc-class-ref in PangolinADManager.o
  "_OBJC_CLASS_$_BUVideoAdView", referenced from:
      objc-class-ref in OpenScreenBaiduADView.o
  "_OBJC_CLASS_$_BUNativeAd", referenced from:
      l__CATEGORY_BUNativeAd_$_HelloTalk_Binary in AdDataProtocol.o
      objc-class-ref in OpenScreenBaiduADView.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ZexiFangkong** [comment]
不知道是官网没更新, 还是兼容没做好
