### ISSUE TITLE
内存泄露 & 内存暴涨

### ISSUE THREAD

**Issue by uzhy1987** [bytedance/Bytedance-UnionAD#80]
1. 信息流视频广告容易导致内存大增
2. 而且销毁实例后，内存并不释放，需要退到后台才一下子释放
3. 退到后台释放后，还是有部分内存没释放

我们使用的sdk版本是3.0.0.2，用swift开发，每个信息流广告都单独用一个BUNativeExpressAdManager生成，滑过一页后就会销毁BUNativeExpressAdManager

请问该怎么优化处理，以便及时释放内存

**Comment by zengyangyang** [comment]
您好，BUNativeExpressAdManager可以重复使用，不需要频繁创建。

**Comment by yh980237697** [comment]
V3001做了优化，请升级到最新版本使用
