### ISSUE TITLE
穿山甲支持iPad吗

### ISSUE THREAD

**Issue by nimo369** [bytedance/Bytedance-UnionAD#86]
原生模板在ipad上布局错乱

**Comment by yh980237697** [comment]
麻烦给一张截图，我们看一下问题

**Comment by chebanyun** [comment]
![image](https://user-images.githubusercontent.com/61813869/89859080-bdabf600-dbd2-11ea-8836-7acc89a5b70e.png)

**Comment by chebanyun** [comment]
同一种样式
