### ISSUE TITLE
3.2.5.0版本什么时候发布到CocoaPods上？

### ISSUE THREAD

**Issue by eroscai** [bytedance/Bytedance-UnionAD#95]
如题。现在就等着穿山甲适配iOS14，之前都是pods方式引入的，不可能临时改回手动引入吧。什么时候会发布到pods上，能否给个时间？

**Comment by WillieWangWei** [comment]
您好，预计今日发布 3.2.5.1 版本，此版本包含了 iOS 14 的适配。发布后，您可以通过 CocoaPods 直接引入到项目中。
