### ISSUE TITLE
请求次数太多以后必现

### ISSUE THREAD

**Issue by xiangrongsu** [bytedance/Bytedance-UnionAD#96]
-08-31 21:18:32.747031+0800 PTGAdSDK_Example[11092:3519031] -[__NSCFString dictionaryValue]: unrecognized selector sent to instance 0x282402880
2020-08-31 21:18:32.747788+0800 PTGAdSDK_Example[11092:3519031] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString dictionaryValue]: unrecognized selector sent to instance 0x282402880'
*** First throw call stack:
(0x185acea48 0x1857f5fa4 0x1859d25a8 0x185ad2af4 0x185ad4a7c 0x10039b4d4 0x10046aca4 0x1003e4ba4 0x1003e4940 0x1003e4898 0x1003a66bc 0x1004b9be8 0x185ad4c20 0x1859a4d30 0x1005fcb98 0x1005fbf48 0x1005e22d8 0x1005aa490 0x1005f3aa0 0x1005f397c 0x1001b11ec 0x1001b14a8 0x189b42e50 0x189579494 0x1895797f8 0x189578814 0x10043a540 0x189b7c3d4 0x189b7d714 0x189b59e2c 0x189bd1fa4 0x189bd4500 0x189bcd374 0x185a4ca00 0x185a4c958 0x185a4c0f0 0x185a4723c 0x185a46adc 0x18f9cc328 0x189b41ae0 0x1001b2988 0x1858d0360)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by WillieWangWei** [comment]
您好，可以提供一下符号化之后的堆栈信息吗？

**Comment by xiangrongsu** [comment]
更新以后好了
