### ISSUE TITLE
[Feature] 是否可以增加不创建测试应用即可使用且一个不绑定bundleid的测试id？以及实时同步更新pod，官网更新pod即更新

### ISSUE THREAD

**Issue by MorningStarJ** [bytedance/Bytedance-UnionAD#97]
## 提出该建议为了测试便利性
通常测试时需使用和bundleid相符合的广告id，且观看激励视频时间较长

## 期望可以使用测试id
测试时更加方便，对开发者更友好，使用测试id不记入收益，期望观看测试全屏视频广告可直接关闭，激励视频广告3，5秒即可关闭

**Comment by leonard-li** [comment]
> ## 提出该建议为了测试便利性
> 通常测试时需使用和bundleid相符合的广告id，且观看激励视频时间较长
> 
> ## 期望可以使用测试id
> 测试时更加方便，对开发者更友好，使用测试id不记入收益，期望观看测试全屏视频广告可直接关闭，激励视频广告3，5秒即可关闭

Demo里面有提供测试用的广告ID，且并不与Bundle ID绑定～
在/Example/BUDemo/BUDemo/App/Macros/BUDSlotID.h里面定义有各种广告类型的广告ID，
在/Example/BUDemo/BUDemo/App/Example/BUDAdManager.m里面定义有appKey。

**Comment by MorningStarJ** [comment]
> > ## 提出该建议为了测试便利性
> > 通常测试时需使用和bundleid相符合的广告id，且观看激励视频时间较长
> > ## 期望可以使用测试id
> > 测试时更加方便，对开发者更友好，使用测试id不记入收益，期望观看测试全屏视频广告可直接关闭，激励视频广告3，5秒即可关闭
> 
> Demo里面有提供测试用的广告ID，且并不与Bundle ID绑定～
> 在/Example/BUDemo/BUDemo/App/Macros/BUDSlotID.h里面定义有各种广告类型的广告ID，
> 在/Example/BUDemo/BUDemo/App/Example/BUDAdManager.m里面定义有appKey。

好的，麻烦了
