### ISSUE TITLE
[BUG] 请求频率过高导致请求失败

### ISSUE THREAD

**Issue by c344081** [bytedance/Bytedance-UnionAD#98]
## Describe the bug | 问题描述
Error Domain=com.bytedance.buadsdk Code=20001 "请求频率过高，请限制单位时间内的广告请求次数。" 

有没有文档说明一下最大限制？

## Environmental information | 环境信息
 - SDK version: | SDK 版本： 3.1.0.9
 - Date and time: | 日期与时间： 2020-09-17 10:51
 - Device model: | 设备型号：  iPhone 6s
 - iOS version: | iOS 版本： 14.0, 13.6.1

## To Reproduce | 如何复现
页面上广告隔段时间刷新一下

**Comment by weigzhong** [comment]
出现这个问题需要优化一下广告的请求频率，避免频繁请求的情况发生
